/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SlickClient);
  }
}(this, function(expect, SlickClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SlickClient.SlickqaUserInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SlickqaUserInfo', function() {
    it('should create an instance of SlickqaUserInfo', function() {
      // uncomment below and update the code to test SlickqaUserInfo
      //var instane = new SlickClient.SlickqaUserInfo();
      //expect(instance).to.be.a(SlickClient.SlickqaUserInfo);
    });

    it('should have the property emailAddress (base name: "EmailAddress")', function() {
      // uncomment below and update the code to test the property emailAddress
      //var instane = new SlickClient.SlickqaUserInfo();
      //expect(instance).to.be();
    });

    it('should have the property permissions (base name: "Permissions")', function() {
      // uncomment below and update the code to test the property permissions
      //var instane = new SlickClient.SlickqaUserInfo();
      //expect(instance).to.be();
    });

    it('should have the property fullName (base name: "FullName")', function() {
      // uncomment below and update the code to test the property fullName
      //var instane = new SlickClient.SlickqaUserInfo();
      //expect(instance).to.be();
    });

    it('should have the property givenName (base name: "GivenName")', function() {
      // uncomment below and update the code to test the property givenName
      //var instane = new SlickClient.SlickqaUserInfo();
      //expect(instance).to.be();
    });

    it('should have the property familyName (base name: "FamilyName")', function() {
      // uncomment below and update the code to test the property familyName
      //var instane = new SlickClient.SlickqaUserInfo();
      //expect(instance).to.be();
    });

    it('should have the property avatarUrl (base name: "AvatarUrl")', function() {
      // uncomment below and update the code to test the property avatarUrl
      //var instane = new SlickClient.SlickqaUserInfo();
      //expect(instance).to.be();
    });

    it('should have the property jobTitle (base name: "JobTitle")', function() {
      // uncomment below and update the code to test the property jobTitle
      //var instane = new SlickClient.SlickqaUserInfo();
      //expect(instance).to.be();
    });

    it('should have the property hashedPassword (base name: "HashedPassword")', function() {
      // uncomment below and update the code to test the property hashedPassword
      //var instane = new SlickClient.SlickqaUserInfo();
      //expect(instance).to.be();
    });

    it('should have the property userPreferences (base name: "UserPreferences")', function() {
      // uncomment below and update the code to test the property userPreferences
      //var instane = new SlickClient.SlickqaUserInfo();
      //expect(instance).to.be();
    });

  });

}));
