// Code generated by protoc-gen-go.
// source: slick.proto
// DO NOT EDIT!

/*
Package slickqa is a generated protocol buffer package.

It is generated from these files:
	slick.proto

It has these top-level messages:
	IsAuthorizedRequest
	IsAuthorizedResponse
	CurrentUserRequest
	UserInfoRequest
	UsersForCompanyQueryRequest
	UsersForProjectQueryRequest
	UsersQueryResponse
	ProjectPermissionInfo
	CompanyPermissionInfo
	SlickPermissionInfo
	UserInfo
	ApiTokenLoginRequest
	PlainUserLoginRequest
	LoginResponse
	Project
	Component
	Feature
	Testcase
	Testplans
	Testruns
*/
package slickqa

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// auth stuff
type IsAuthorizedRequest struct {
	CompanyName string ` protobuf:"bytes,1,opt,name=CompanyName"        json:"CompanyName,omitempty"`
	ProjectName string ` protobuf:"bytes,2,opt,name=ProjectName"        json:"ProjectName,omitempty"`
	Permission  uint32 ` protobuf:"varint,3,opt,name=Permission"        json:"Permission,omitempty"`
}

func (m *IsAuthorizedRequest) Reset()                    { *m = IsAuthorizedRequest{} }
func (m *IsAuthorizedRequest) String() string            { return proto.CompactTextString(m) }
func (*IsAuthorizedRequest) ProtoMessage()               {}
func (*IsAuthorizedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IsAuthorizedRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *IsAuthorizedRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *IsAuthorizedRequest) GetPermission() uint32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

type IsAuthorizedResponse struct {
	Allowed bool   `protobuf:"varint,1,opt,name=Allowed"           json:"Allowed"`
	Message string ` protobuf:"bytes,2,opt,name=Message"            json:"Message,omitempty"`
}

func (m *IsAuthorizedResponse) Reset()                    { *m = IsAuthorizedResponse{} }
func (m *IsAuthorizedResponse) String() string            { return proto.CompactTextString(m) }
func (*IsAuthorizedResponse) ProtoMessage()               {}
func (*IsAuthorizedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IsAuthorizedResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

func (m *IsAuthorizedResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CurrentUserRequest struct {
}

func (m *CurrentUserRequest) Reset()                    { *m = CurrentUserRequest{} }
func (m *CurrentUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CurrentUserRequest) ProtoMessage()               {}
func (*CurrentUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type UserInfoRequest struct {
	EmailAddress string ` protobuf:"bytes,1,opt,name=EmailAddress"       json:"EmailAddress,omitempty"`
}

func (m *UserInfoRequest) Reset()                    { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()               {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserInfoRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type UsersForCompanyQueryRequest struct {
	CompanyName string ` protobuf:"bytes,1,opt,name=CompanyName"        json:"CompanyName,omitempty"`
}

func (m *UsersForCompanyQueryRequest) Reset()                    { *m = UsersForCompanyQueryRequest{} }
func (m *UsersForCompanyQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*UsersForCompanyQueryRequest) ProtoMessage()               {}
func (*UsersForCompanyQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UsersForCompanyQueryRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

type UsersForProjectQueryRequest struct {
	CompanyName string ` protobuf:"bytes,1,opt,name=CompanyName"        json:"CompanyName,omitempty"`
	ProjectName string ` protobuf:"bytes,2,opt,name=ProjectName"        json:"ProjectName,omitempty"`
}

func (m *UsersForProjectQueryRequest) Reset()                    { *m = UsersForProjectQueryRequest{} }
func (m *UsersForProjectQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*UsersForProjectQueryRequest) ProtoMessage()               {}
func (*UsersForProjectQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UsersForProjectQueryRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *UsersForProjectQueryRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type UsersQueryResponse struct {
	Users []*UserInfo ` protobuf:"bytes,1,rep,name=users"              json:"users,omitempty"`
}

func (m *UsersQueryResponse) Reset()                    { *m = UsersQueryResponse{} }
func (m *UsersQueryResponse) String() string            { return proto.CompactTextString(m) }
func (*UsersQueryResponse) ProtoMessage()               {}
func (*UsersQueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UsersQueryResponse) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type ProjectPermissionInfo struct {
	ProjectName string   ` protobuf:"bytes,1,opt,name=ProjectName"        json:"ProjectName,omitempty"  bson:"name"`
	Roles       []string ` protobuf:"bytes,2,rep,name=Roles"              json:"Roles,omitempty"        bson:"roles"`
}

func (m *ProjectPermissionInfo) Reset()                    { *m = ProjectPermissionInfo{} }
func (m *ProjectPermissionInfo) String() string            { return proto.CompactTextString(m) }
func (*ProjectPermissionInfo) ProtoMessage()               {}
func (*ProjectPermissionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ProjectPermissionInfo) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *ProjectPermissionInfo) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CompanyPermissionInfo struct {
	CompanyName  string                   ` protobuf:"bytes,1,opt,name=CompanyName"        json:"CompanyName,omitempty"  bson:"name"`
	CompanyAdmin uint32                   ` protobuf:"varint,2,opt,name=CompanyAdmin"      json:"CompanyAdmin,omitempty"  bson:"admin"`
	Projects     []*ProjectPermissionInfo ` protobuf:"bytes,3,rep,name=Projects"           json:"Projects,omitempty"     bson:"projects"`
}

func (m *CompanyPermissionInfo) Reset()                    { *m = CompanyPermissionInfo{} }
func (m *CompanyPermissionInfo) String() string            { return proto.CompactTextString(m) }
func (*CompanyPermissionInfo) ProtoMessage()               {}
func (*CompanyPermissionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CompanyPermissionInfo) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *CompanyPermissionInfo) GetCompanyAdmin() uint32 {
	if m != nil {
		return m.CompanyAdmin
	}
	return 0
}

func (m *CompanyPermissionInfo) GetProjects() []*ProjectPermissionInfo {
	if m != nil {
		return m.Projects
	}
	return nil
}

type SlickPermissionInfo struct {
	SlickAdmin uint32                   ` protobuf:"varint,1,opt,name=SlickAdmin"        json:"SlickAdmin,omitempty"   bson:"slickAdmin"`
	Companies  []*CompanyPermissionInfo ` protobuf:"bytes,2,rep,name=Companies"          json:"Companies,omitempty"    bson:"companies"`
}

func (m *SlickPermissionInfo) Reset()                    { *m = SlickPermissionInfo{} }
func (m *SlickPermissionInfo) String() string            { return proto.CompactTextString(m) }
func (*SlickPermissionInfo) ProtoMessage()               {}
func (*SlickPermissionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SlickPermissionInfo) GetSlickAdmin() uint32 {
	if m != nil {
		return m.SlickAdmin
	}
	return 0
}

func (m *SlickPermissionInfo) GetCompanies() []*CompanyPermissionInfo {
	if m != nil {
		return m.Companies
	}
	return nil
}

type UserInfo struct {
	EmailAddress   string               ` protobuf:"bytes,1,opt,name=EmailAddress"       json:"EmailAddress,omitempty"  bson:"_id"`
	Permissions    *SlickPermissionInfo ` protobuf:"bytes,2,opt,name=Permissions"        json:"Permissions,omitempty"  bson:"permissions"`
	FullName       string               ` protobuf:"bytes,3,opt,name=FullName"           json:"FullName,omitempty"     bson:"fullName"`
	GivenName      string               ` protobuf:"bytes,4,opt,name=GivenName"          json:"GivenName,omitempty"    bson:"givenName"`
	FamilyName     string               ` protobuf:"bytes,5,opt,name=FamilyName"         json:"FamilyName,omitempty"   bson:"familyName"`
	AvatarUrl      string               ` protobuf:"bytes,6,opt,name=AvatarUrl"          json:"AvatarUrl,omitempty"    bson:"avatarUrl"`
	JobTitle       string               ` protobuf:"bytes,7,opt,name=JobTitle"           json:"JobTitle,omitempty"     bson:"title"`
	HashedPassword string               ` protobuf:"bytes,8,opt,name=HashedPassword"     json:"HashedPassword,omitempty"  bson:"hashedPassword"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UserInfo) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *UserInfo) GetPermissions() *SlickPermissionInfo {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *UserInfo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserInfo) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *UserInfo) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *UserInfo) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *UserInfo) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *UserInfo) GetHashedPassword() string {
	if m != nil {
		return m.HashedPassword
	}
	return ""
}

type ApiTokenLoginRequest struct {
	Token string ` protobuf:"bytes,1,opt,name=Token"              json:"Token,omitempty"`
}

func (m *ApiTokenLoginRequest) Reset()                    { *m = ApiTokenLoginRequest{} }
func (m *ApiTokenLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*ApiTokenLoginRequest) ProtoMessage()               {}
func (*ApiTokenLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ApiTokenLoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PlainUserLoginRequest struct {
	UserName string ` protobuf:"bytes,1,opt,name=UserName"           json:"UserName,omitempty"`
	Password string ` protobuf:"bytes,2,opt,name=Password"           json:"Password,omitempty"`
}

func (m *PlainUserLoginRequest) Reset()                    { *m = PlainUserLoginRequest{} }
func (m *PlainUserLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*PlainUserLoginRequest) ProtoMessage()               {}
func (*PlainUserLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PlainUserLoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PlainUserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Success bool      `protobuf:"varint,1,opt,name=Success"           json:"Success"`
	Token   string    ` protobuf:"bytes,2,opt,name=Token"              json:"Token,omitempty"`
	User    *UserInfo ` protobuf:"bytes,3,opt,name=User"               json:"User,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *LoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

// slick objects
type Project struct {
	Id              []byte                     ` protobuf:"bytes,1,opt,name=Id,proto3"          json:"Id,omitempty"           bson:"_id,omitempty"`
	Name            string                     ` protobuf:"bytes,2,opt,name=Name"               json:"Name,omitempty"         bson:"name"`
	AutomationTools []string                   ` protobuf:"bytes,3,rep,name=AutomationTools"    json:"AutomationTools,omitempty"  bson:"automationTools"`
	Tags            []string                   ` protobuf:"bytes,4,rep,name=Tags"               json:"Tags,omitempty"         bson:"tags"`
	Attributes      map[string]string          `   protobuf:"bytes,5,rep,name=Attributes"         json:"Attributes,omitempty"   protobuf_key:"bytes,1,opt,name=key"   protobuf_val:"bytes,2,opt,name=value"  bson:"attributes"`
	LastUpdated     *google_protobuf.Timestamp ` protobuf:"bytes,6,opt,name=LastUpdated"        json:"LastUpdated,omitempty"  bson:"lastUpdated"`
}

func (m *Project) Reset()                    { *m = Project{} }
func (m *Project) String() string            { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()               {}
func (*Project) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Project) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetAutomationTools() []string {
	if m != nil {
		return m.AutomationTools
	}
	return nil
}

func (m *Project) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Project) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Project) GetLastUpdated() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type Component struct {
	Id      []byte `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Project string `protobuf:"bytes,3,opt,name=Project" json:"Project,omitempty"`
}

func (m *Component) Reset()                    { *m = Component{} }
func (m *Component) String() string            { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()               {}
func (*Component) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Component) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Component) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Component) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type Feature struct {
	Id          []byte `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	ComponentId []byte `protobuf:"bytes,3,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	ProjectId   string `protobuf:"bytes,4,opt,name=ProjectId" json:"ProjectId,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Feature) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetComponentId() []byte {
	if m != nil {
		return m.ComponentId
	}
	return nil
}

func (m *Feature) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type Testcase struct {
	Id               []byte   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name             string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	AutomationKey    string   `protobuf:"bytes,3,opt,name=AutomationKey" json:"AutomationKey,omitempty"`
	AutomationTool   string   `protobuf:"bytes,4,opt,name=AutomationTool" json:"AutomationTool,omitempty"`
	ComponentId      []byte   `protobuf:"bytes,5,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	Deleted          bool     `protobuf:"varint,6,opt,name=Deleted" json:"Deleted,omitempty"`
	ImportanceRating int32    `protobuf:"varint,7,opt,name=ImportanceRating" json:"ImportanceRating,omitempty"`
	InactiveNotes    []string `protobuf:"bytes,8,rep,name=InactiveNotes" json:"InactiveNotes,omitempty"`
	ProjectId        string   `protobuf:"bytes,9,opt,name=ProjectId" json:"ProjectId,omitempty"`
	StabilityRating  int32    `protobuf:"varint,10,opt,name=StabilityRating" json:"StabilityRating,omitempty"`
	Steps            []string `protobuf:"bytes,11,rep,name=Steps" json:"Steps,omitempty"`
	Tags             []string `protobuf:"bytes,12,rep,name=Tags" json:"Tags,omitempty"`
}

func (m *Testcase) Reset()                    { *m = Testcase{} }
func (m *Testcase) String() string            { return proto.CompactTextString(m) }
func (*Testcase) ProtoMessage()               {}
func (*Testcase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Testcase) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Testcase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Testcase) GetAutomationKey() string {
	if m != nil {
		return m.AutomationKey
	}
	return ""
}

func (m *Testcase) GetAutomationTool() string {
	if m != nil {
		return m.AutomationTool
	}
	return ""
}

func (m *Testcase) GetComponentId() []byte {
	if m != nil {
		return m.ComponentId
	}
	return nil
}

func (m *Testcase) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Testcase) GetImportanceRating() int32 {
	if m != nil {
		return m.ImportanceRating
	}
	return 0
}

func (m *Testcase) GetInactiveNotes() []string {
	if m != nil {
		return m.InactiveNotes
	}
	return nil
}

func (m *Testcase) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Testcase) GetStabilityRating() int32 {
	if m != nil {
		return m.StabilityRating
	}
	return 0
}

func (m *Testcase) GetSteps() []string {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Testcase) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Testplans struct {
	Id   []byte `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *Testplans) Reset()                    { *m = Testplans{} }
func (m *Testplans) String() string            { return proto.CompactTextString(m) }
func (*Testplans) ProtoMessage()               {}
func (*Testplans) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *Testplans) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Testplans) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Testruns struct {
	Id          []byte                     `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name        string                     `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	ProjectId   string                     `protobuf:"bytes,3,opt,name=ProjectId" json:"ProjectId,omitempty"`
	Build       string                     `protobuf:"bytes,4,opt,name=Build" json:"Build,omitempty"`
	RunStarted  *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=RunStarted" json:"RunStarted,omitempty"`
	RunFinished *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=RunFinished" json:"RunFinished,omitempty"`
	State       string                     `protobuf:"bytes,7,opt,name=State" json:"State,omitempty"`
	TestplanId  string                     `protobuf:"bytes,8,opt,name=TestplanId" json:"TestplanId,omitempty"`
}

func (m *Testruns) Reset()                    { *m = Testruns{} }
func (m *Testruns) String() string            { return proto.CompactTextString(m) }
func (*Testruns) ProtoMessage()               {}
func (*Testruns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Testruns) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Testruns) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Testruns) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Testruns) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func (m *Testruns) GetRunStarted() *google_protobuf.Timestamp {
	if m != nil {
		return m.RunStarted
	}
	return nil
}

func (m *Testruns) GetRunFinished() *google_protobuf.Timestamp {
	if m != nil {
		return m.RunFinished
	}
	return nil
}

func (m *Testruns) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Testruns) GetTestplanId() string {
	if m != nil {
		return m.TestplanId
	}
	return ""
}

func init() {
	proto.RegisterType((*IsAuthorizedRequest)(nil), "slickqa.IsAuthorizedRequest")
	proto.RegisterType((*IsAuthorizedResponse)(nil), "slickqa.IsAuthorizedResponse")
	proto.RegisterType((*CurrentUserRequest)(nil), "slickqa.CurrentUserRequest")
	proto.RegisterType((*UserInfoRequest)(nil), "slickqa.UserInfoRequest")
	proto.RegisterType((*UsersForCompanyQueryRequest)(nil), "slickqa.UsersForCompanyQueryRequest")
	proto.RegisterType((*UsersForProjectQueryRequest)(nil), "slickqa.UsersForProjectQueryRequest")
	proto.RegisterType((*UsersQueryResponse)(nil), "slickqa.UsersQueryResponse")
	proto.RegisterType((*ProjectPermissionInfo)(nil), "slickqa.ProjectPermissionInfo")
	proto.RegisterType((*CompanyPermissionInfo)(nil), "slickqa.CompanyPermissionInfo")
	proto.RegisterType((*SlickPermissionInfo)(nil), "slickqa.SlickPermissionInfo")
	proto.RegisterType((*UserInfo)(nil), "slickqa.UserInfo")
	proto.RegisterType((*ApiTokenLoginRequest)(nil), "slickqa.ApiTokenLoginRequest")
	proto.RegisterType((*PlainUserLoginRequest)(nil), "slickqa.PlainUserLoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "slickqa.LoginResponse")
	proto.RegisterType((*Project)(nil), "slickqa.Project")
	proto.RegisterType((*Component)(nil), "slickqa.Component")
	proto.RegisterType((*Feature)(nil), "slickqa.Feature")
	proto.RegisterType((*Testcase)(nil), "slickqa.Testcase")
	proto.RegisterType((*Testplans)(nil), "slickqa.Testplans")
	proto.RegisterType((*Testruns)(nil), "slickqa.Testruns")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	IsAuthorized(ctx context.Context, in *IsAuthorizedRequest, opts ...grpc.CallOption) (*IsAuthorizedResponse, error)
	LoginWithToken(ctx context.Context, in *ApiTokenLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	LoginWithCredentials(ctx context.Context, in *PlainUserLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) IsAuthorized(ctx context.Context, in *IsAuthorizedRequest, opts ...grpc.CallOption) (*IsAuthorizedResponse, error) {
	out := new(IsAuthorizedResponse)
	err := grpc.Invoke(ctx, "/slickqa.Auth/IsAuthorized", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) LoginWithToken(ctx context.Context, in *ApiTokenLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/slickqa.Auth/LoginWithToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) LoginWithCredentials(ctx context.Context, in *PlainUserLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/slickqa.Auth/LoginWithCredentials", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	IsAuthorized(context.Context, *IsAuthorizedRequest) (*IsAuthorizedResponse, error)
	LoginWithToken(context.Context, *ApiTokenLoginRequest) (*LoginResponse, error)
	LoginWithCredentials(context.Context, *PlainUserLoginRequest) (*LoginResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_IsAuthorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAuthorizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).IsAuthorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Auth/IsAuthorized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).IsAuthorized(ctx, req.(*IsAuthorizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_LoginWithToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiTokenLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).LoginWithToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Auth/LoginWithToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).LoginWithToken(ctx, req.(*ApiTokenLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_LoginWithCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlainUserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).LoginWithCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Auth/LoginWithCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).LoginWithCredentials(ctx, req.(*PlainUserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "slickqa.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAuthorized",
			Handler:    _Auth_IsAuthorized_Handler,
		},
		{
			MethodName: "LoginWithToken",
			Handler:    _Auth_LoginWithToken_Handler,
		},
		{
			MethodName: "LoginWithCredentials",
			Handler:    _Auth_LoginWithCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slick.proto",
}

// Client API for Users service

type UsersClient interface {
	GetCurrentUserInfo(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
	GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error)
	GetUsersForCompany(ctx context.Context, in *UsersForCompanyQueryRequest, opts ...grpc.CallOption) (*UsersQueryResponse, error)
	GetUsersForProject(ctx context.Context, in *UsersForProjectQueryRequest, opts ...grpc.CallOption) (*UsersQueryResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) GetCurrentUserInfo(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := grpc.Invoke(ctx, "/slickqa.Users/GetCurrentUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := grpc.Invoke(ctx, "/slickqa.Users/GetUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUsersForCompany(ctx context.Context, in *UsersForCompanyQueryRequest, opts ...grpc.CallOption) (*UsersQueryResponse, error) {
	out := new(UsersQueryResponse)
	err := grpc.Invoke(ctx, "/slickqa.Users/GetUsersForCompany", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUsersForProject(ctx context.Context, in *UsersForProjectQueryRequest, opts ...grpc.CallOption) (*UsersQueryResponse, error) {
	out := new(UsersQueryResponse)
	err := grpc.Invoke(ctx, "/slickqa.Users/GetUsersForProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersServer interface {
	GetCurrentUserInfo(context.Context, *CurrentUserRequest) (*UserInfo, error)
	GetUserInfo(context.Context, *UserInfoRequest) (*UserInfo, error)
	GetUsersForCompany(context.Context, *UsersForCompanyQueryRequest) (*UsersQueryResponse, error)
	GetUsersForProject(context.Context, *UsersForProjectQueryRequest) (*UsersQueryResponse, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_GetCurrentUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetCurrentUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Users/GetCurrentUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetCurrentUserInfo(ctx, req.(*CurrentUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Users/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUsersForCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersForCompanyQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUsersForCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Users/GetUsersForCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUsersForCompany(ctx, req.(*UsersForCompanyQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUsersForProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersForProjectQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUsersForProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Users/GetUsersForProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUsersForProject(ctx, req.(*UsersForProjectQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "slickqa.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentUserInfo",
			Handler:    _Users_GetCurrentUserInfo_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Users_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUsersForCompany",
			Handler:    _Users_GetUsersForCompany_Handler,
		},
		{
			MethodName: "GetUsersForProject",
			Handler:    _Users_GetUsersForProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slick.proto",
}

func init() { proto.RegisterFile("slick.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x96, 0xed, 0xb8, 0xb1, 0x8f, 0x93, 0xa6, 0x9d, 0xba, 0xb0, 0x72, 0x4a, 0xb0, 0x86, 0xb6,
	0x44, 0x85, 0xda, 0x22, 0x15, 0x12, 0x54, 0x2d, 0xc5, 0xfd, 0x49, 0x70, 0x29, 0xa5, 0x6c, 0x5c,
	0x21, 0x71, 0xc5, 0xd8, 0x3b, 0x71, 0x86, 0xae, 0x67, 0xdc, 0x9d, 0xd9, 0x54, 0x26, 0xca, 0x0d,
	0xe2, 0x09, 0x0a, 0x37, 0xbc, 0x42, 0x5f, 0x87, 0x57, 0xe0, 0x86, 0x67, 0x80, 0x0b, 0x34, 0x33,
	0xfb, 0x6f, 0xa7, 0x31, 0x77, 0x7b, 0x7e, 0xe6, 0xfc, 0x7c, 0x73, 0xce, 0x99, 0xb3, 0xd0, 0x90,
	0x3e, 0x1b, 0xbd, 0xe8, 0x4c, 0x03, 0xa1, 0x04, 0x5a, 0x35, 0xc4, 0x4b, 0xd2, 0x7a, 0x7f, 0x2c,
	0xc4, 0xd8, 0xa7, 0x5d, 0xc3, 0x1e, 0x86, 0x07, 0x5d, 0xc5, 0x26, 0x54, 0x2a, 0x32, 0x99, 0x5a,
	0xcd, 0xd6, 0x95, 0x48, 0x81, 0x4c, 0x59, 0x97, 0x70, 0x2e, 0x14, 0x51, 0x4c, 0x70, 0x69, 0xa5,
	0x78, 0x06, 0x97, 0xfa, 0xb2, 0x17, 0xaa, 0x43, 0x11, 0xb0, 0x9f, 0xa9, 0xe7, 0xd2, 0x97, 0x21,
	0x95, 0x0a, 0xb5, 0xa1, 0xf1, 0x40, 0x4c, 0xa6, 0x84, 0xcf, 0x9e, 0x92, 0x09, 0x75, 0x4a, 0xed,
	0xd2, 0x76, 0xdd, 0xcd, 0xb2, 0xb4, 0xc6, 0xb3, 0x40, 0xfc, 0x44, 0x47, 0xca, 0x68, 0x94, 0xad,
	0x46, 0x86, 0x85, 0xb6, 0x00, 0x9e, 0xd1, 0x60, 0xc2, 0xa4, 0x64, 0x82, 0x3b, 0x95, 0x76, 0x69,
	0x7b, 0xdd, 0xcd, 0x70, 0xf0, 0x63, 0x68, 0xe6, 0x5d, 0xcb, 0xa9, 0xe0, 0x92, 0x22, 0x07, 0x56,
	0x7b, 0xbe, 0x2f, 0x5e, 0x51, 0xcf, 0xf8, 0xad, 0xb9, 0x31, 0xa9, 0x25, 0xdf, 0x50, 0x29, 0xc9,
	0x38, 0xf6, 0x17, 0x93, 0xb8, 0x09, 0xe8, 0x41, 0x18, 0x04, 0x94, 0xab, 0xe7, 0x92, 0x06, 0x51,
	0x16, 0xf8, 0x53, 0xd8, 0xd0, 0x64, 0x9f, 0x1f, 0x88, 0x38, 0x31, 0x0c, 0x6b, 0x8f, 0x26, 0x84,
	0xf9, 0x3d, 0xcf, 0x0b, 0xa8, 0x94, 0x51, 0x66, 0x39, 0x1e, 0xbe, 0x07, 0x9b, 0xfa, 0x98, 0xdc,
	0x15, 0x41, 0x94, 0xf1, 0x77, 0x21, 0x0d, 0x66, 0x4b, 0x63, 0x83, 0x49, 0x6a, 0x20, 0x02, 0xe4,
	0xff, 0x19, 0x38, 0x1b, 0x5c, 0x7c, 0x17, 0x90, 0x71, 0x11, 0x19, 0x8e, 0xa0, 0xfb, 0x10, 0xaa,
	0xa1, 0xe6, 0x3a, 0xa5, 0x76, 0x65, 0xbb, 0xb1, 0x73, 0xb1, 0x13, 0x55, 0x49, 0x27, 0x81, 0xc1,
	0xca, 0xf1, 0xb7, 0x70, 0x39, 0xb2, 0x96, 0x5e, 0x88, 0x96, 0x17, 0x3d, 0x97, 0xe6, 0xaf, 0xb5,
	0x09, 0x55, 0x57, 0xf8, 0x54, 0x3a, 0xe5, 0x76, 0x65, 0xbb, 0xee, 0x5a, 0x02, 0xff, 0x51, 0x82,
	0xcb, 0x51, 0x06, 0xf3, 0x16, 0xcf, 0xc8, 0x16, 0xc3, 0x5a, 0x44, 0xf6, 0xbc, 0x09, 0xe3, 0x26,
	0xdd, 0x75, 0x37, 0xc7, 0x43, 0xb7, 0xa1, 0x16, 0x05, 0x21, 0x9d, 0x8a, 0x49, 0x6e, 0x2b, 0x49,
	0x6e, 0x61, 0x26, 0x6e, 0xa2, 0x8f, 0x25, 0x5c, 0xda, 0xd7, 0xaa, 0x85, 0xc0, 0xb6, 0x00, 0x0c,
	0xdb, 0x3a, 0x2d, 0xd9, 0xfa, 0x4c, 0x39, 0xe8, 0x0e, 0xd4, 0x6d, 0x08, 0x2c, 0x4a, 0x36, 0xeb,
	0x73, 0x61, 0xae, 0x6e, 0x7a, 0x00, 0xbf, 0x29, 0x43, 0x2d, 0x46, 0x7d, 0x99, 0xaa, 0x43, 0x5f,
	0x40, 0x23, 0xb5, 0x26, 0x0d, 0x08, 0x8d, 0x9d, 0x2b, 0x89, 0xc3, 0x05, 0x19, 0xb8, 0xd9, 0x03,
	0xa8, 0x05, 0xb5, 0xdd, 0xd0, 0xf7, 0x0d, 0xc8, 0x15, 0x63, 0x3f, 0xa1, 0xd1, 0x15, 0xa8, 0xef,
	0xb1, 0x23, 0xca, 0x8d, 0x70, 0xc5, 0x08, 0x53, 0x86, 0x06, 0x62, 0x97, 0x4c, 0x98, 0x6f, 0x2f,
	0xa8, 0x6a, 0xc4, 0x19, 0x8e, 0x3e, 0xdd, 0x3b, 0x22, 0x8a, 0x04, 0xcf, 0x03, 0xdf, 0x39, 0x67,
	0x4f, 0x27, 0x0c, 0xed, 0xf7, 0xb1, 0x18, 0x0e, 0x98, 0xf2, 0xa9, 0xb3, 0x6a, 0xfd, 0xc6, 0x34,
	0xba, 0x0e, 0xe7, 0xbf, 0x22, 0xf2, 0x90, 0x7a, 0xcf, 0x88, 0x94, 0xaf, 0x44, 0xe0, 0x39, 0x35,
	0xa3, 0x51, 0xe0, 0xe2, 0x8f, 0xa1, 0xd9, 0x9b, 0xb2, 0x81, 0x78, 0x41, 0xf9, 0x13, 0x31, 0x66,
	0x3c, 0xee, 0x94, 0x26, 0x54, 0x0d, 0x33, 0x02, 0xcc, 0x12, 0xa6, 0x78, 0x7d, 0xc2, 0xb8, 0x86,
	0x37, 0xa7, 0xde, 0xb2, 0x90, 0x67, 0xea, 0x2c, 0xa1, 0xb5, 0x2c, 0x09, 0xc2, 0xf6, 0x53, 0x42,
	0xe3, 0x03, 0x58, 0x8f, 0xec, 0xa4, 0x23, 0x68, 0x3f, 0x1c, 0x8d, 0xe2, 0xab, 0xaa, 0xb9, 0x31,
	0x99, 0x46, 0x54, 0xce, 0x44, 0x84, 0xae, 0xc1, 0x8a, 0x76, 0x64, 0x70, 0x5f, 0xd8, 0x76, 0x46,
	0xac, 0x6b, 0x62, 0x35, 0xaa, 0x4a, 0x74, 0x1e, 0xca, 0x7d, 0x3b, 0xe0, 0xd6, 0xdc, 0x72, 0xdf,
	0x43, 0x08, 0x56, 0x32, 0xbd, 0x6e, 0xbe, 0xd1, 0x36, 0x6c, 0xf4, 0x42, 0x25, 0x26, 0x66, 0x62,
	0x0f, 0x84, 0xf0, 0x6d, 0xed, 0xd7, 0xdd, 0x22, 0x5b, 0x9f, 0x1e, 0x90, 0xb1, 0x74, 0x56, 0x8c,
	0xd8, 0x7c, 0xa3, 0x2f, 0x01, 0x7a, 0x4a, 0x05, 0x6c, 0x18, 0x2a, 0x2a, 0x9d, 0xaa, 0x29, 0xe0,
	0x76, 0xb1, 0x69, 0x3a, 0xa9, 0xca, 0x23, 0xae, 0x82, 0x99, 0x9b, 0x39, 0x83, 0xee, 0x40, 0xe3,
	0x09, 0x91, 0xea, 0xf9, 0xd4, 0x23, 0x8a, 0x7a, 0xe6, 0xea, 0x1b, 0x3b, 0xad, 0x8e, 0x7d, 0x50,
	0x3a, 0xf1, 0x8b, 0xd3, 0x19, 0xc4, 0x2f, 0x8e, 0x9b, 0x55, 0x6f, 0xdd, 0x85, 0x8d, 0x82, 0x71,
	0x74, 0x01, 0x2a, 0x2f, 0xe8, 0x2c, 0xba, 0x1b, 0xfd, 0xa9, 0xf1, 0x3c, 0x22, 0x7e, 0x18, 0xe7,
	0x6d, 0x89, 0xdb, 0xe5, 0xcf, 0x4a, 0xb8, 0x6f, 0xdb, 0x4f, 0x70, 0xca, 0x97, 0x43, 0xcb, 0x49,
	0xc0, 0x8d, 0xea, 0x3f, 0x26, 0xf1, 0x04, 0x56, 0x77, 0x29, 0x51, 0x61, 0x40, 0x97, 0x32, 0x14,
	0x4d, 0x2c, 0xe3, 0xb9, 0xef, 0x19, 0x63, 0x6b, 0x6e, 0x96, 0xa5, 0x3b, 0x22, 0xb2, 0xdd, 0xf7,
	0xe2, 0x7e, 0x4a, 0x18, 0xf8, 0xdf, 0x32, 0xd4, 0x06, 0x54, 0xaa, 0x11, 0x91, 0xcb, 0x39, 0xbc,
	0x0a, 0xeb, 0xe9, 0x85, 0x7e, 0x4d, 0x67, 0x51, 0xfc, 0x79, 0xa6, 0x6e, 0xa6, 0xfc, 0xb5, 0x47,
	0x9e, 0x0b, 0xdc, 0x62, 0xf8, 0xd5, 0xf9, 0xf0, 0x1d, 0x58, 0x7d, 0x48, 0x7d, 0x1a, 0xdf, 0x69,
	0xcd, 0x8d, 0x49, 0x74, 0x03, 0x2e, 0xf4, 0x27, 0x53, 0x11, 0x28, 0xc2, 0x47, 0xd4, 0x25, 0x8a,
	0xf1, 0xb1, 0x69, 0xea, 0xaa, 0x3b, 0xc7, 0xd7, 0x51, 0xf7, 0x39, 0x19, 0x29, 0x76, 0x44, 0x9f,
	0x0a, 0x5d, 0x62, 0x35, 0x53, 0x7c, 0x79, 0x66, 0x1e, 0xaa, 0x7a, 0x01, 0x2a, 0x5d, 0xe1, 0xfb,
	0x8a, 0x0c, 0x99, 0xcf, 0xd4, 0x2c, 0x72, 0x07, 0xc6, 0x5d, 0x91, 0xad, 0x0b, 0x65, 0x5f, 0xd1,
	0xa9, 0x74, 0x1a, 0xf6, 0xd9, 0x31, 0x44, 0x52, 0xf7, 0x6b, 0x69, 0xdd, 0xe3, 0x2e, 0xd4, 0x35,
	0xfa, 0x53, 0x9f, 0x70, 0xb9, 0x0c, 0xfc, 0xf8, 0x75, 0x74, 0x5f, 0x41, 0xb8, 0xdc, 0x81, 0x7c,
	0x4e, 0x95, 0x62, 0x4e, 0x4d, 0xa8, 0xde, 0x0f, 0x99, 0x1f, 0x17, 0x86, 0x25, 0xd0, 0x6d, 0x00,
	0x37, 0xe4, 0xfb, 0x8a, 0x04, 0x1a, 0xf6, 0xea, 0x99, 0xad, 0x94, 0xd1, 0xd6, 0x7d, 0xe8, 0x86,
	0x7c, 0x97, 0x71, 0xa6, 0xa7, 0xe6, 0x32, 0x7d, 0x98, 0x51, 0xb7, 0xc8, 0x11, 0x15, 0x4f, 0x67,
	0x4b, 0xe8, 0xa1, 0x1f, 0xa3, 0xd4, 0x8f, 0xc7, 0x72, 0x86, 0xb3, 0xf3, 0x4f, 0x19, 0x56, 0xf4,
	0x72, 0x86, 0x7e, 0x2f, 0xc1, 0x5a, 0x76, 0x4f, 0x43, 0xe9, 0x9b, 0xb4, 0x60, 0x73, 0x6c, 0xbd,
	0x77, 0x8a, 0xd4, 0x4e, 0x56, 0xbc, 0xf7, 0xcb, 0x9f, 0x7f, 0xfd, 0x56, 0xee, 0xa1, 0x7b, 0x76,
	0x1f, 0x0d, 0xd5, 0x61, 0x97, 0x65, 0xf4, 0xba, 0xc7, 0x99, 0xc5, 0xe0, 0xa4, 0x7b, 0x9c, 0x59,
	0x3c, 0x34, 0x95, 0x3c, 0x77, 0x27, 0x48, 0xc2, 0x79, 0x33, 0xb3, 0xbf, 0x67, 0xea, 0xd0, 0x0e,
	0xe1, 0xd4, 0xf3, 0xa2, 0xb7, 0xa4, 0xf5, 0x4e, 0x22, 0xce, 0xcd, 0x7a, 0x7c, 0xc3, 0x44, 0x74,
	0x15, 0xe1, 0x34, 0x22, 0x5f, 0x2b, 0xdc, 0x7c, 0xc5, 0xd4, 0xe1, 0x4d, 0xa5, 0xed, 0x74, 0x8f,
	0x8d, 0xb9, 0x13, 0x34, 0x86, 0x66, 0xe2, 0xf4, 0x41, 0x40, 0x3d, 0xca, 0x15, 0x23, 0xbe, 0x44,
	0x99, 0x5d, 0x64, 0xd1, 0xc3, 0x74, 0xaa, 0xef, 0x77, 0x8d, 0xef, 0x8b, 0x78, 0xa3, 0xe0, 0x7b,
	0xe7, 0xef, 0x0a, 0x54, 0xcd, 0x7e, 0x87, 0x7e, 0x04, 0xb4, 0x47, 0x55, 0x66, 0xb9, 0x35, 0x0b,
	0xc5, 0x66, 0xba, 0x88, 0xcc, 0xad, 0xbd, 0xad, 0xf9, 0xf7, 0x07, 0xb7, 0x8c, 0xa3, 0x26, 0x42,
	0xc6, 0x91, 0xd9, 0x01, 0xbb, 0x23, 0x7b, 0x12, 0x0d, 0xa1, 0xb1, 0x47, 0x53, 0xd3, 0xce, 0xfc,
	0xeb, 0x75, 0xba, 0xdd, 0xeb, 0xc6, 0x6e, 0x1b, 0x6d, 0x65, 0xec, 0x32, 0x7e, 0x20, 0xba, 0xc7,
	0xd9, 0xdd, 0xe6, 0x04, 0xfd, 0x5a, 0x32, 0x69, 0x14, 0xd6, 0x6a, 0x74, 0x35, 0x67, 0xf1, 0x94,
	0x85, 0xbb, 0xb5, 0x99, 0xd7, 0xca, 0xad, 0xbc, 0xf8, 0x23, 0x13, 0xc1, 0x35, 0xf4, 0x41, 0x26,
	0x82, 0xe1, 0xec, 0xe6, 0xc8, 0xda, 0xc9, 0xd7, 0x13, 0x7a, 0x9d, 0x0f, 0x23, 0x7e, 0x8b, 0xe7,
	0xc3, 0x58, 0xb0, 0xb6, 0xbf, 0x3d, 0x8c, 0xcf, 0x4d, 0x18, 0xb7, 0xd0, 0x27, 0xf9, 0x30, 0xa6,
	0xd6, 0xce, 0xdb, 0xca, 0xfa, 0xfe, 0x43, 0xd8, 0x1c, 0x89, 0x49, 0x62, 0x7c, 0xe4, 0x33, 0xca,
	0x55, 0xd2, 0xd5, 0x3f, 0xc4, 0x7f, 0x7a, 0x6f, 0xca, 0x6f, 0x53, 0x1b, 0x9e, 0x33, 0x5f, 0xb7,
	0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x28, 0xd2, 0xfa, 0xf5, 0x26, 0x0e, 0x00, 0x00,
}
