// Code generated by protoc-gen-go. DO NOT EDIT.
// source: slick.proto

/*
Package slickqa is a generated protocol buffer package.

It is generated from these files:
	slick.proto

It has these top-level messages:
	IsAuthorizedRequest
	IsAuthorizedResponse
	CurrentUserRequest
	UserInfoRequest
	UsersForCompanyQueryRequest
	UsersForProjectQueryRequest
	UsersQueryResponse
	ProjectPermissionInfo
	CompanyPermissionInfo
	SlickPermissionInfo
	Preferences
	CompanySettings
	UserInfo
	ApiTokenLoginRequest
	PlainUserLoginRequest
	LoginResponse
	VersionRequest
	VersionInfoResponse
	CompanySettingsRequest
	AddUserRequest
	AvailableCompanySettingsRequest
	AvailableCompanySettings
	Link
	ProjectIdentity
	Project
	ComponentIdentity
	Component
	Feature
	Testcase
	Testplans
	Testruns
*/
package slickqa

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// auth stuff
type IsAuthorizedRequest struct {
	CompanyName string ` protobuf:"bytes,1,opt,name=CompanyName"              json:"CompanyName,omitempty"`
	ProjectName string ` protobuf:"bytes,2,opt,name=ProjectName"              json:"ProjectName,omitempty"`
	Permission  uint32 ` protobuf:"varint,3,opt,name=Permission"              json:"Permission,omitempty"`
}

func (m *IsAuthorizedRequest) Reset()                    { *m = IsAuthorizedRequest{} }
func (m *IsAuthorizedRequest) String() string            { return proto.CompactTextString(m) }
func (*IsAuthorizedRequest) ProtoMessage()               {}
func (*IsAuthorizedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IsAuthorizedRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *IsAuthorizedRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *IsAuthorizedRequest) GetPermission() uint32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

type IsAuthorizedResponse struct {
	Allowed bool   `protobuf:"varint,1,opt,name=Allowed"                 json:"Allowed"`
	Message string ` protobuf:"bytes,2,opt,name=Message"                  json:"Message,omitempty"`
}

func (m *IsAuthorizedResponse) Reset()                    { *m = IsAuthorizedResponse{} }
func (m *IsAuthorizedResponse) String() string            { return proto.CompactTextString(m) }
func (*IsAuthorizedResponse) ProtoMessage()               {}
func (*IsAuthorizedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IsAuthorizedResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

func (m *IsAuthorizedResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CurrentUserRequest struct {
}

func (m *CurrentUserRequest) Reset()                    { *m = CurrentUserRequest{} }
func (m *CurrentUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CurrentUserRequest) ProtoMessage()               {}
func (*CurrentUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type UserInfoRequest struct {
	EmailAddress string ` protobuf:"bytes,1,opt,name=EmailAddress"             json:"EmailAddress,omitempty"`
}

func (m *UserInfoRequest) Reset()                    { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()               {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserInfoRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type UsersForCompanyQueryRequest struct {
	CompanyName string ` protobuf:"bytes,1,opt,name=CompanyName"              json:"CompanyName,omitempty"`
}

func (m *UsersForCompanyQueryRequest) Reset()                    { *m = UsersForCompanyQueryRequest{} }
func (m *UsersForCompanyQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*UsersForCompanyQueryRequest) ProtoMessage()               {}
func (*UsersForCompanyQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UsersForCompanyQueryRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

type UsersForProjectQueryRequest struct {
	CompanyName string ` protobuf:"bytes,1,opt,name=CompanyName"              json:"CompanyName,omitempty"`
	ProjectName string ` protobuf:"bytes,2,opt,name=ProjectName"              json:"ProjectName,omitempty"`
}

func (m *UsersForProjectQueryRequest) Reset()                    { *m = UsersForProjectQueryRequest{} }
func (m *UsersForProjectQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*UsersForProjectQueryRequest) ProtoMessage()               {}
func (*UsersForProjectQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UsersForProjectQueryRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *UsersForProjectQueryRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type UsersQueryResponse struct {
	Users []*UserInfo ` protobuf:"bytes,1,rep,name=users"                    json:"users,omitempty"`
}

func (m *UsersQueryResponse) Reset()                    { *m = UsersQueryResponse{} }
func (m *UsersQueryResponse) String() string            { return proto.CompactTextString(m) }
func (*UsersQueryResponse) ProtoMessage()               {}
func (*UsersQueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UsersQueryResponse) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type ProjectPermissionInfo struct {
	ProjectName string   ` protobuf:"bytes,1,opt,name=ProjectName"              json:"ProjectName,omitempty"  bson:"name"`
	Roles       []string ` protobuf:"bytes,2,rep,name=Roles"                    json:"Roles,omitempty"        bson:"roles"`
}

func (m *ProjectPermissionInfo) Reset()                    { *m = ProjectPermissionInfo{} }
func (m *ProjectPermissionInfo) String() string            { return proto.CompactTextString(m) }
func (*ProjectPermissionInfo) ProtoMessage()               {}
func (*ProjectPermissionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ProjectPermissionInfo) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *ProjectPermissionInfo) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CompanyPermissionInfo struct {
	CompanyName  string                   ` protobuf:"bytes,1,opt,name=CompanyName"              json:"CompanyName,omitempty"  bson:"name"`
	CompanyAdmin uint32                   ` protobuf:"varint,2,opt,name=CompanyAdmin"            json:"CompanyAdmin,omitempty"  bson:"admin"`
	Projects     []*ProjectPermissionInfo ` protobuf:"bytes,3,rep,name=Projects"                 json:"Projects,omitempty"     bson:"projects"`
}

func (m *CompanyPermissionInfo) Reset()                    { *m = CompanyPermissionInfo{} }
func (m *CompanyPermissionInfo) String() string            { return proto.CompactTextString(m) }
func (*CompanyPermissionInfo) ProtoMessage()               {}
func (*CompanyPermissionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CompanyPermissionInfo) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *CompanyPermissionInfo) GetCompanyAdmin() uint32 {
	if m != nil {
		return m.CompanyAdmin
	}
	return 0
}

func (m *CompanyPermissionInfo) GetProjects() []*ProjectPermissionInfo {
	if m != nil {
		return m.Projects
	}
	return nil
}

type SlickPermissionInfo struct {
	SlickAdmin uint32                   ` protobuf:"varint,1,opt,name=SlickAdmin"              json:"SlickAdmin,omitempty"   bson:"slickAdmin"`
	Companies  []*CompanyPermissionInfo ` protobuf:"bytes,2,rep,name=Companies"                json:"Companies,omitempty"    bson:"companies"`
}

func (m *SlickPermissionInfo) Reset()                    { *m = SlickPermissionInfo{} }
func (m *SlickPermissionInfo) String() string            { return proto.CompactTextString(m) }
func (*SlickPermissionInfo) ProtoMessage()               {}
func (*SlickPermissionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SlickPermissionInfo) GetSlickAdmin() uint32 {
	if m != nil {
		return m.SlickAdmin
	}
	return 0
}

func (m *SlickPermissionInfo) GetCompanies() []*CompanyPermissionInfo {
	if m != nil {
		return m.Companies
	}
	return nil
}

type Preferences struct {
	HomeUrl       string  ` protobuf:"bytes,1,opt,name=HomeUrl"                  json:"HomeUrl,omitempty"      bson:"home"`
	Theme         string  ` protobuf:"bytes,2,opt,name=Theme"                    json:"Theme,omitempty"        bson:"theme"`
	BackgroundUrl string  ` protobuf:"bytes,3,opt,name=BackgroundUrl"            json:"BackgroundUrl,omitempty"  bson:"background"`
	Favorites     []*Link ` protobuf:"bytes,4,rep,name=Favorites"                json:"Favorites,omitempty"    bson:"favorites"`
}

func (m *Preferences) Reset()                    { *m = Preferences{} }
func (m *Preferences) String() string            { return proto.CompactTextString(m) }
func (*Preferences) ProtoMessage()               {}
func (*Preferences) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Preferences) GetHomeUrl() string {
	if m != nil {
		return m.HomeUrl
	}
	return ""
}

func (m *Preferences) GetTheme() string {
	if m != nil {
		return m.Theme
	}
	return ""
}

func (m *Preferences) GetBackgroundUrl() string {
	if m != nil {
		return m.BackgroundUrl
	}
	return ""
}

func (m *Preferences) GetFavorites() []*Link {
	if m != nil {
		return m.Favorites
	}
	return nil
}

type CompanySettings struct {
	CompanyName            string       ` protobuf:"bytes,1,opt,name=CompanyName"              json:"CompanyName,omitempty"  bson:"_id"`
	UserPreferenceTemplate *Preferences ` protobuf:"bytes,2,opt,name=UserPreferenceTemplate"   json:"UserPreferenceTemplate,omitempty"  bson:"user-preferences"`
	CustomIconUrl          string       ` protobuf:"bytes,3,opt,name=CustomIconUrl"            json:"CustomIconUrl,omitempty"  bson:"icon-url"`
	Links                  []*Link      ` protobuf:"bytes,4,rep,name=Links"                    json:"Links,omitempty"        bson:"links"`
}

func (m *CompanySettings) Reset()                    { *m = CompanySettings{} }
func (m *CompanySettings) String() string            { return proto.CompactTextString(m) }
func (*CompanySettings) ProtoMessage()               {}
func (*CompanySettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CompanySettings) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *CompanySettings) GetUserPreferenceTemplate() *Preferences {
	if m != nil {
		return m.UserPreferenceTemplate
	}
	return nil
}

func (m *CompanySettings) GetCustomIconUrl() string {
	if m != nil {
		return m.CustomIconUrl
	}
	return ""
}

func (m *CompanySettings) GetLinks() []*Link {
	if m != nil {
		return m.Links
	}
	return nil
}

type UserInfo struct {
	EmailAddress    string               ` protobuf:"bytes,1,opt,name=EmailAddress"             json:"EmailAddress,omitempty"  bson:"_id"`
	Permissions     *SlickPermissionInfo ` protobuf:"bytes,2,opt,name=Permissions"              json:"Permissions,omitempty"  bson:"permissions"`
	FullName        string               ` protobuf:"bytes,3,opt,name=FullName"                 json:"FullName,omitempty"     bson:"fullName"`
	GivenName       string               ` protobuf:"bytes,4,opt,name=GivenName"                json:"GivenName,omitempty"    bson:"givenName"`
	FamilyName      string               ` protobuf:"bytes,5,opt,name=FamilyName"               json:"FamilyName,omitempty"   bson:"familyName"`
	AvatarUrl       string               ` protobuf:"bytes,6,opt,name=AvatarUrl"                json:"AvatarUrl,omitempty"    bson:"avatarUrl"`
	JobTitle        string               ` protobuf:"bytes,7,opt,name=JobTitle"                 json:"JobTitle,omitempty"     bson:"title"`
	HashedPassword  string               ` protobuf:"bytes,8,opt,name=HashedPassword"           json:"HashedPassword,omitempty"  bson:"hashedPassword"`
	UserPreferences *Preferences         ` protobuf:"bytes,9,opt,name=UserPreferences"          json:"UserPreferences,omitempty"  bson:"preferences"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *UserInfo) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *UserInfo) GetPermissions() *SlickPermissionInfo {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *UserInfo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserInfo) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *UserInfo) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *UserInfo) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *UserInfo) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *UserInfo) GetHashedPassword() string {
	if m != nil {
		return m.HashedPassword
	}
	return ""
}

func (m *UserInfo) GetUserPreferences() *Preferences {
	if m != nil {
		return m.UserPreferences
	}
	return nil
}

type ApiTokenLoginRequest struct {
	Token string ` protobuf:"bytes,1,opt,name=Token"                    json:"Token,omitempty"`
}

func (m *ApiTokenLoginRequest) Reset()                    { *m = ApiTokenLoginRequest{} }
func (m *ApiTokenLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*ApiTokenLoginRequest) ProtoMessage()               {}
func (*ApiTokenLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ApiTokenLoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PlainUserLoginRequest struct {
	UserName string ` protobuf:"bytes,1,opt,name=UserName"                 json:"UserName,omitempty"`
	Password string ` protobuf:"bytes,2,opt,name=Password"                 json:"Password,omitempty"`
}

func (m *PlainUserLoginRequest) Reset()                    { *m = PlainUserLoginRequest{} }
func (m *PlainUserLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*PlainUserLoginRequest) ProtoMessage()               {}
func (*PlainUserLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PlainUserLoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PlainUserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Success bool      `protobuf:"varint,1,opt,name=Success"                 json:"Success"`
	Token   string    ` protobuf:"bytes,2,opt,name=Token"                    json:"Token,omitempty"`
	User    *UserInfo ` protobuf:"bytes,3,opt,name=User"                     json:"User,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *LoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type VersionRequest struct {
}

func (m *VersionRequest) Reset()                    { *m = VersionRequest{} }
func (m *VersionRequest) String() string            { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()               {}
func (*VersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type VersionInfoResponse struct {
	Version string ` protobuf:"bytes,1,opt,name=Version"                  json:"Version,omitempty"`
}

func (m *VersionInfoResponse) Reset()                    { *m = VersionInfoResponse{} }
func (m *VersionInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionInfoResponse) ProtoMessage()               {}
func (*VersionInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *VersionInfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type CompanySettingsRequest struct {
	CompanyName string ` protobuf:"bytes,1,opt,name=CompanyName"              json:"CompanyName,omitempty"`
}

func (m *CompanySettingsRequest) Reset()                    { *m = CompanySettingsRequest{} }
func (m *CompanySettingsRequest) String() string            { return proto.CompactTextString(m) }
func (*CompanySettingsRequest) ProtoMessage()               {}
func (*CompanySettingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CompanySettingsRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

type AddUserRequest struct {
	UserEmail   string                 ` protobuf:"bytes,1,opt,name=UserEmail"                json:"UserEmail,omitempty"`
	CompanyName string                 ` protobuf:"bytes,2,opt,name=CompanyName"              json:"CompanyName,omitempty"`
	Permissions *CompanyPermissionInfo ` protobuf:"bytes,3,opt,name=Permissions"              json:"Permissions,omitempty"`
}

func (m *AddUserRequest) Reset()                    { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()               {}
func (*AddUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *AddUserRequest) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *AddUserRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *AddUserRequest) GetPermissions() *CompanyPermissionInfo {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type AvailableCompanySettingsRequest struct {
}

func (m *AvailableCompanySettingsRequest) Reset()         { *m = AvailableCompanySettingsRequest{} }
func (m *AvailableCompanySettingsRequest) String() string { return proto.CompactTextString(m) }
func (*AvailableCompanySettingsRequest) ProtoMessage()    {}
func (*AvailableCompanySettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{20}
}

type AvailableCompanySettings struct {
	Companies []*CompanySettings `protobuf:"bytes,1,rep,name=Companies"                json:"Companies"`
}

func (m *AvailableCompanySettings) Reset()                    { *m = AvailableCompanySettings{} }
func (m *AvailableCompanySettings) String() string            { return proto.CompactTextString(m) }
func (*AvailableCompanySettings) ProtoMessage()               {}
func (*AvailableCompanySettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *AvailableCompanySettings) GetCompanies() []*CompanySettings {
	if m != nil {
		return m.Companies
	}
	return nil
}

type Link struct {
	Url  string ` protobuf:"bytes,1,opt,name=Url"                      json:"Url,omitempty"          bson:"url"`
	Name string ` protobuf:"bytes,2,opt,name=Name"                     json:"Name,omitempty"         bson:"name"`
	// to be used by UI, examples include iframe, video, picture, external, html-source, etc
	UIViewType string ` protobuf:"bytes,3,opt,name=UIViewType"               json:"UIViewType,omitempty"   bson:"ui-view"`
}

func (m *Link) Reset()                    { *m = Link{} }
func (m *Link) String() string            { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()               {}
func (*Link) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Link) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Link) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Link) GetUIViewType() string {
	if m != nil {
		return m.UIViewType
	}
	return ""
}

type ProjectIdentity struct {
	Company string ` protobuf:"bytes,1,opt,name=Company"                  json:"Company,omitempty"      bson:"company"`
	Name    string ` protobuf:"bytes,2,opt,name=Name"                     json:"Name,omitempty"         bson:"name"`
}

func (m *ProjectIdentity) Reset()                    { *m = ProjectIdentity{} }
func (m *ProjectIdentity) String() string            { return proto.CompactTextString(m) }
func (*ProjectIdentity) ProtoMessage()               {}
func (*ProjectIdentity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ProjectIdentity) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *ProjectIdentity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Project struct {
	Id              *ProjectIdentity           ` protobuf:"bytes,1,opt,name=Id"                       json:"Id,omitempty"           bson:"_id"`
	AutomationTools []string                   ` protobuf:"bytes,3,rep,name=AutomationTools"          json:"AutomationTools,omitempty"  bson:"automationTools"`
	Tags            []string                   ` protobuf:"bytes,4,rep,name=Tags"                     json:"Tags,omitempty"         bson:"tags"`
	Attributes      map[string]string          `   protobuf:"bytes,5,rep,name=Attributes"               json:"Attributes,omitempty"   protobuf_key:"bytes,1,opt,name=key"   protobuf_val:"bytes,2,opt,name=value"  bson:"attributes"`
	LastUpdated     *google_protobuf.Timestamp ` protobuf:"bytes,6,opt,name=LastUpdated"              json:"LastUpdated,omitempty"  bson:"lastUpdated"`
}

func (m *Project) Reset()                    { *m = Project{} }
func (m *Project) String() string            { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()               {}
func (*Project) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *Project) GetId() *ProjectIdentity {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Project) GetAutomationTools() []string {
	if m != nil {
		return m.AutomationTools
	}
	return nil
}

func (m *Project) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Project) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Project) GetLastUpdated() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type ComponentIdentity struct {
	Project *ProjectIdentity ` protobuf:"bytes,1,opt,name=Project"                  json:"Project,omitempty"      bson:"project"`
	Name    string           ` protobuf:"bytes,2,opt,name=Name"                     json:"Name,omitempty"         bson:"name"`
}

func (m *ComponentIdentity) Reset()                    { *m = ComponentIdentity{} }
func (m *ComponentIdentity) String() string            { return proto.CompactTextString(m) }
func (*ComponentIdentity) ProtoMessage()               {}
func (*ComponentIdentity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ComponentIdentity) GetProject() *ProjectIdentity {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *ComponentIdentity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Component struct {
	Id          *ComponentIdentity `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Description string             `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
}

func (m *Component) Reset()                    { *m = Component{} }
func (m *Component) String() string            { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()               {}
func (*Component) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *Component) GetId() *ComponentIdentity {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Component) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Feature struct {
	Id          []byte `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	ComponentId []byte `protobuf:"bytes,3,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	ProjectId   string `protobuf:"bytes,4,opt,name=ProjectId" json:"ProjectId,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *Feature) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetComponentId() []byte {
	if m != nil {
		return m.ComponentId
	}
	return nil
}

func (m *Feature) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type Testcase struct {
	Id               []byte   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name             string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	AutomationKey    string   `protobuf:"bytes,3,opt,name=AutomationKey" json:"AutomationKey,omitempty"`
	AutomationTool   string   `protobuf:"bytes,4,opt,name=AutomationTool" json:"AutomationTool,omitempty"`
	ComponentId      []byte   `protobuf:"bytes,5,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	Deleted          bool     `protobuf:"varint,6,opt,name=Deleted" json:"Deleted,omitempty"`
	ImportanceRating int32    `protobuf:"varint,7,opt,name=ImportanceRating" json:"ImportanceRating,omitempty"`
	InactiveNotes    []string `protobuf:"bytes,8,rep,name=InactiveNotes" json:"InactiveNotes,omitempty"`
	ProjectId        string   `protobuf:"bytes,9,opt,name=ProjectId" json:"ProjectId,omitempty"`
	StabilityRating  int32    `protobuf:"varint,10,opt,name=StabilityRating" json:"StabilityRating,omitempty"`
	Steps            []string `protobuf:"bytes,11,rep,name=Steps" json:"Steps,omitempty"`
	Tags             []string `protobuf:"bytes,12,rep,name=Tags" json:"Tags,omitempty"`
}

func (m *Testcase) Reset()                    { *m = Testcase{} }
func (m *Testcase) String() string            { return proto.CompactTextString(m) }
func (*Testcase) ProtoMessage()               {}
func (*Testcase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *Testcase) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Testcase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Testcase) GetAutomationKey() string {
	if m != nil {
		return m.AutomationKey
	}
	return ""
}

func (m *Testcase) GetAutomationTool() string {
	if m != nil {
		return m.AutomationTool
	}
	return ""
}

func (m *Testcase) GetComponentId() []byte {
	if m != nil {
		return m.ComponentId
	}
	return nil
}

func (m *Testcase) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Testcase) GetImportanceRating() int32 {
	if m != nil {
		return m.ImportanceRating
	}
	return 0
}

func (m *Testcase) GetInactiveNotes() []string {
	if m != nil {
		return m.InactiveNotes
	}
	return nil
}

func (m *Testcase) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Testcase) GetStabilityRating() int32 {
	if m != nil {
		return m.StabilityRating
	}
	return 0
}

func (m *Testcase) GetSteps() []string {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Testcase) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Testplans struct {
	Id   []byte `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *Testplans) Reset()                    { *m = Testplans{} }
func (m *Testplans) String() string            { return proto.CompactTextString(m) }
func (*Testplans) ProtoMessage()               {}
func (*Testplans) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *Testplans) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Testplans) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Testruns struct {
	Id          []byte                     `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name        string                     `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	ProjectId   string                     `protobuf:"bytes,3,opt,name=ProjectId" json:"ProjectId,omitempty"`
	Build       string                     `protobuf:"bytes,4,opt,name=Build" json:"Build,omitempty"`
	RunStarted  *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=RunStarted" json:"RunStarted,omitempty"`
	RunFinished *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=RunFinished" json:"RunFinished,omitempty"`
	State       string                     `protobuf:"bytes,7,opt,name=State" json:"State,omitempty"`
	TestplanId  string                     `protobuf:"bytes,8,opt,name=TestplanId" json:"TestplanId,omitempty"`
}

func (m *Testruns) Reset()                    { *m = Testruns{} }
func (m *Testruns) String() string            { return proto.CompactTextString(m) }
func (*Testruns) ProtoMessage()               {}
func (*Testruns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *Testruns) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Testruns) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Testruns) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Testruns) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func (m *Testruns) GetRunStarted() *google_protobuf.Timestamp {
	if m != nil {
		return m.RunStarted
	}
	return nil
}

func (m *Testruns) GetRunFinished() *google_protobuf.Timestamp {
	if m != nil {
		return m.RunFinished
	}
	return nil
}

func (m *Testruns) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Testruns) GetTestplanId() string {
	if m != nil {
		return m.TestplanId
	}
	return ""
}

func init() {
	proto.RegisterType((*IsAuthorizedRequest)(nil), "slickqa.IsAuthorizedRequest")
	proto.RegisterType((*IsAuthorizedResponse)(nil), "slickqa.IsAuthorizedResponse")
	proto.RegisterType((*CurrentUserRequest)(nil), "slickqa.CurrentUserRequest")
	proto.RegisterType((*UserInfoRequest)(nil), "slickqa.UserInfoRequest")
	proto.RegisterType((*UsersForCompanyQueryRequest)(nil), "slickqa.UsersForCompanyQueryRequest")
	proto.RegisterType((*UsersForProjectQueryRequest)(nil), "slickqa.UsersForProjectQueryRequest")
	proto.RegisterType((*UsersQueryResponse)(nil), "slickqa.UsersQueryResponse")
	proto.RegisterType((*ProjectPermissionInfo)(nil), "slickqa.ProjectPermissionInfo")
	proto.RegisterType((*CompanyPermissionInfo)(nil), "slickqa.CompanyPermissionInfo")
	proto.RegisterType((*SlickPermissionInfo)(nil), "slickqa.SlickPermissionInfo")
	proto.RegisterType((*Preferences)(nil), "slickqa.Preferences")
	proto.RegisterType((*CompanySettings)(nil), "slickqa.CompanySettings")
	proto.RegisterType((*UserInfo)(nil), "slickqa.UserInfo")
	proto.RegisterType((*ApiTokenLoginRequest)(nil), "slickqa.ApiTokenLoginRequest")
	proto.RegisterType((*PlainUserLoginRequest)(nil), "slickqa.PlainUserLoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "slickqa.LoginResponse")
	proto.RegisterType((*VersionRequest)(nil), "slickqa.VersionRequest")
	proto.RegisterType((*VersionInfoResponse)(nil), "slickqa.VersionInfoResponse")
	proto.RegisterType((*CompanySettingsRequest)(nil), "slickqa.CompanySettingsRequest")
	proto.RegisterType((*AddUserRequest)(nil), "slickqa.AddUserRequest")
	proto.RegisterType((*AvailableCompanySettingsRequest)(nil), "slickqa.AvailableCompanySettingsRequest")
	proto.RegisterType((*AvailableCompanySettings)(nil), "slickqa.AvailableCompanySettings")
	proto.RegisterType((*Link)(nil), "slickqa.Link")
	proto.RegisterType((*ProjectIdentity)(nil), "slickqa.ProjectIdentity")
	proto.RegisterType((*Project)(nil), "slickqa.Project")
	proto.RegisterType((*ComponentIdentity)(nil), "slickqa.ComponentIdentity")
	proto.RegisterType((*Component)(nil), "slickqa.Component")
	proto.RegisterType((*Feature)(nil), "slickqa.Feature")
	proto.RegisterType((*Testcase)(nil), "slickqa.Testcase")
	proto.RegisterType((*Testplans)(nil), "slickqa.Testplans")
	proto.RegisterType((*Testruns)(nil), "slickqa.Testruns")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	IsAuthorized(ctx context.Context, in *IsAuthorizedRequest, opts ...grpc.CallOption) (*IsAuthorizedResponse, error)
	LoginWithToken(ctx context.Context, in *ApiTokenLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	LoginWithCredentials(ctx context.Context, in *PlainUserLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) IsAuthorized(ctx context.Context, in *IsAuthorizedRequest, opts ...grpc.CallOption) (*IsAuthorizedResponse, error) {
	out := new(IsAuthorizedResponse)
	err := grpc.Invoke(ctx, "/slickqa.Auth/IsAuthorized", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) LoginWithToken(ctx context.Context, in *ApiTokenLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/slickqa.Auth/LoginWithToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) LoginWithCredentials(ctx context.Context, in *PlainUserLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/slickqa.Auth/LoginWithCredentials", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	IsAuthorized(context.Context, *IsAuthorizedRequest) (*IsAuthorizedResponse, error)
	LoginWithToken(context.Context, *ApiTokenLoginRequest) (*LoginResponse, error)
	LoginWithCredentials(context.Context, *PlainUserLoginRequest) (*LoginResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_IsAuthorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAuthorizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).IsAuthorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Auth/IsAuthorized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).IsAuthorized(ctx, req.(*IsAuthorizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_LoginWithToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiTokenLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).LoginWithToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Auth/LoginWithToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).LoginWithToken(ctx, req.(*ApiTokenLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_LoginWithCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlainUserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).LoginWithCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Auth/LoginWithCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).LoginWithCredentials(ctx, req.(*PlainUserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "slickqa.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAuthorized",
			Handler:    _Auth_IsAuthorized_Handler,
		},
		{
			MethodName: "LoginWithToken",
			Handler:    _Auth_LoginWithToken_Handler,
		},
		{
			MethodName: "LoginWithCredentials",
			Handler:    _Auth_LoginWithCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slick.proto",
}

// Client API for Users service

type UsersClient interface {
	GetCurrentUserInfo(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
	GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error)
	GetUsersForCompany(ctx context.Context, in *UsersForCompanyQueryRequest, opts ...grpc.CallOption) (*UsersQueryResponse, error)
	GetUsersForProject(ctx context.Context, in *UsersForProjectQueryRequest, opts ...grpc.CallOption) (*UsersQueryResponse, error)
	UpdateUser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*UserInfo, error)
	AddUserToCompany(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) GetCurrentUserInfo(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := grpc.Invoke(ctx, "/slickqa.Users/GetCurrentUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := grpc.Invoke(ctx, "/slickqa.Users/GetUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUsersForCompany(ctx context.Context, in *UsersForCompanyQueryRequest, opts ...grpc.CallOption) (*UsersQueryResponse, error) {
	out := new(UsersQueryResponse)
	err := grpc.Invoke(ctx, "/slickqa.Users/GetUsersForCompany", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUsersForProject(ctx context.Context, in *UsersForProjectQueryRequest, opts ...grpc.CallOption) (*UsersQueryResponse, error) {
	out := new(UsersQueryResponse)
	err := grpc.Invoke(ctx, "/slickqa.Users/GetUsersForProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateUser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := grpc.Invoke(ctx, "/slickqa.Users/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) AddUserToCompany(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := grpc.Invoke(ctx, "/slickqa.Users/AddUserToCompany", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersServer interface {
	GetCurrentUserInfo(context.Context, *CurrentUserRequest) (*UserInfo, error)
	GetUserInfo(context.Context, *UserInfoRequest) (*UserInfo, error)
	GetUsersForCompany(context.Context, *UsersForCompanyQueryRequest) (*UsersQueryResponse, error)
	GetUsersForProject(context.Context, *UsersForProjectQueryRequest) (*UsersQueryResponse, error)
	UpdateUser(context.Context, *UserInfo) (*UserInfo, error)
	AddUserToCompany(context.Context, *AddUserRequest) (*UserInfo, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_GetCurrentUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetCurrentUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Users/GetCurrentUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetCurrentUserInfo(ctx, req.(*CurrentUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Users/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUsersForCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersForCompanyQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUsersForCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Users/GetUsersForCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUsersForCompany(ctx, req.(*UsersForCompanyQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUsersForProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersForProjectQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUsersForProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Users/GetUsersForProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUsersForProject(ctx, req.(*UsersForProjectQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Users/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateUser(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_AddUserToCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).AddUserToCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Users/AddUserToCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).AddUserToCompany(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "slickqa.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentUserInfo",
			Handler:    _Users_GetCurrentUserInfo_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Users_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUsersForCompany",
			Handler:    _Users_GetUsersForCompany_Handler,
		},
		{
			MethodName: "GetUsersForProject",
			Handler:    _Users_GetUsersForProject_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Users_UpdateUser_Handler,
		},
		{
			MethodName: "AddUserToCompany",
			Handler:    _Users_AddUserToCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slick.proto",
}

// Client API for Company service

type CompanyClient interface {
	GetCompanySettings(ctx context.Context, in *CompanySettingsRequest, opts ...grpc.CallOption) (*CompanySettings, error)
	GetAvailableCompanySettings(ctx context.Context, in *AvailableCompanySettingsRequest, opts ...grpc.CallOption) (*AvailableCompanySettings, error)
	UpdateCompanySettings(ctx context.Context, in *CompanySettings, opts ...grpc.CallOption) (*CompanySettings, error)
	CreateCompanySettings(ctx context.Context, in *CompanySettings, opts ...grpc.CallOption) (*CompanySettings, error)
}

type companyClient struct {
	cc *grpc.ClientConn
}

func NewCompanyClient(cc *grpc.ClientConn) CompanyClient {
	return &companyClient{cc}
}

func (c *companyClient) GetCompanySettings(ctx context.Context, in *CompanySettingsRequest, opts ...grpc.CallOption) (*CompanySettings, error) {
	out := new(CompanySettings)
	err := grpc.Invoke(ctx, "/slickqa.Company/GetCompanySettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyClient) GetAvailableCompanySettings(ctx context.Context, in *AvailableCompanySettingsRequest, opts ...grpc.CallOption) (*AvailableCompanySettings, error) {
	out := new(AvailableCompanySettings)
	err := grpc.Invoke(ctx, "/slickqa.Company/GetAvailableCompanySettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyClient) UpdateCompanySettings(ctx context.Context, in *CompanySettings, opts ...grpc.CallOption) (*CompanySettings, error) {
	out := new(CompanySettings)
	err := grpc.Invoke(ctx, "/slickqa.Company/UpdateCompanySettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyClient) CreateCompanySettings(ctx context.Context, in *CompanySettings, opts ...grpc.CallOption) (*CompanySettings, error) {
	out := new(CompanySettings)
	err := grpc.Invoke(ctx, "/slickqa.Company/CreateCompanySettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Company service

type CompanyServer interface {
	GetCompanySettings(context.Context, *CompanySettingsRequest) (*CompanySettings, error)
	GetAvailableCompanySettings(context.Context, *AvailableCompanySettingsRequest) (*AvailableCompanySettings, error)
	UpdateCompanySettings(context.Context, *CompanySettings) (*CompanySettings, error)
	CreateCompanySettings(context.Context, *CompanySettings) (*CompanySettings, error)
}

func RegisterCompanyServer(s *grpc.Server, srv CompanyServer) {
	s.RegisterService(&_Company_serviceDesc, srv)
}

func _Company_GetCompanySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanySettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).GetCompanySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Company/GetCompanySettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).GetCompanySettings(ctx, req.(*CompanySettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Company_GetAvailableCompanySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailableCompanySettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).GetAvailableCompanySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Company/GetAvailableCompanySettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).GetAvailableCompanySettings(ctx, req.(*AvailableCompanySettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Company_UpdateCompanySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanySettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).UpdateCompanySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Company/UpdateCompanySettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).UpdateCompanySettings(ctx, req.(*CompanySettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _Company_CreateCompanySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanySettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).CreateCompanySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Company/CreateCompanySettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).CreateCompanySettings(ctx, req.(*CompanySettings))
	}
	return interceptor(ctx, in, info, handler)
}

var _Company_serviceDesc = grpc.ServiceDesc{
	ServiceName: "slickqa.Company",
	HandlerType: (*CompanyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCompanySettings",
			Handler:    _Company_GetCompanySettings_Handler,
		},
		{
			MethodName: "GetAvailableCompanySettings",
			Handler:    _Company_GetAvailableCompanySettings_Handler,
		},
		{
			MethodName: "UpdateCompanySettings",
			Handler:    _Company_UpdateCompanySettings_Handler,
		},
		{
			MethodName: "CreateCompanySettings",
			Handler:    _Company_CreateCompanySettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slick.proto",
}

// Client API for Version service

type VersionClient interface {
	GetFullVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionInfoResponse, error)
}

type versionClient struct {
	cc *grpc.ClientConn
}

func NewVersionClient(cc *grpc.ClientConn) VersionClient {
	return &versionClient{cc}
}

func (c *versionClient) GetFullVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionInfoResponse, error) {
	out := new(VersionInfoResponse)
	err := grpc.Invoke(ctx, "/slickqa.Version/GetFullVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Version service

type VersionServer interface {
	GetFullVersion(context.Context, *VersionRequest) (*VersionInfoResponse, error)
}

func RegisterVersionServer(s *grpc.Server, srv VersionServer) {
	s.RegisterService(&_Version_serviceDesc, srv)
}

func _Version_GetFullVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServer).GetFullVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slickqa.Version/GetFullVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServer).GetFullVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Version_serviceDesc = grpc.ServiceDesc{
	ServiceName: "slickqa.Version",
	HandlerType: (*VersionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullVersion",
			Handler:    _Version_GetFullVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slick.proto",
}

func init() { proto.RegisterFile("slick.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1839 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5f, 0x6f, 0x63, 0x47,
	0x15, 0x97, 0x9d, 0xb8, 0xb1, 0x8f, 0xf3, 0xaf, 0xb3, 0xde, 0xc5, 0x75, 0x42, 0x36, 0x3b, 0x4d,
	0xdb, 0x28, 0x65, 0x63, 0x91, 0x0a, 0x04, 0x51, 0xdb, 0xad, 0x37, 0xdb, 0xa4, 0x2e, 0xa1, 0x2c,
	0x37, 0xde, 0xf2, 0x4f, 0x48, 0x4c, 0xec, 0x49, 0x32, 0xcd, 0xf5, 0x1d, 0xf7, 0xce, 0xdc, 0xac,
	0xc2, 0x2a, 0x2f, 0x15, 0x1f, 0x00, 0x2d, 0xbc, 0xf0, 0x15, 0x78, 0x42, 0xe2, 0x6b, 0xf0, 0xc6,
	0x47, 0x80, 0x27, 0x3e, 0x03, 0x42, 0x68, 0xfe, 0xdd, 0x3b, 0xf7, 0xda, 0x4e, 0x8c, 0xc4, 0x9b,
	0xcf, 0xb9, 0x67, 0xce, 0xef, 0xfc, 0x9d, 0x73, 0xc6, 0x50, 0x17, 0x21, 0xeb, 0x5f, 0xee, 0x8e,
	0x62, 0x2e, 0x39, 0x5a, 0xd0, 0xc4, 0xd7, 0xa4, 0xf5, 0xf0, 0x9c, 0xf3, 0xf3, 0x90, 0xb6, 0x35,
	0xfb, 0x34, 0x39, 0x6b, 0x4b, 0x36, 0xa4, 0x42, 0x92, 0xe1, 0xc8, 0x48, 0xb6, 0xd6, 0xad, 0x00,
	0x19, 0xb1, 0x36, 0x89, 0x22, 0x2e, 0x89, 0x64, 0x3c, 0x12, 0xe6, 0x2b, 0xbe, 0x86, 0x7b, 0x5d,
	0xd1, 0x49, 0xe4, 0x05, 0x8f, 0xd9, 0x6f, 0xe9, 0x20, 0xa0, 0x5f, 0x27, 0x54, 0x48, 0xb4, 0x09,
	0xf5, 0x03, 0x3e, 0x1c, 0x91, 0xe8, 0xfa, 0x0b, 0x32, 0xa4, 0xcd, 0xd2, 0x66, 0x69, 0xbb, 0x16,
	0xf8, 0x2c, 0x25, 0xf1, 0x3c, 0xe6, 0x5f, 0xd1, 0xbe, 0xd4, 0x12, 0x65, 0x23, 0xe1, 0xb1, 0xd0,
	0x06, 0xc0, 0x73, 0x1a, 0x0f, 0x99, 0x10, 0x8c, 0x47, 0xcd, 0xb9, 0xcd, 0xd2, 0xf6, 0x52, 0xe0,
	0x71, 0xf0, 0xe7, 0xd0, 0xc8, 0x43, 0x8b, 0x11, 0x8f, 0x04, 0x45, 0x4d, 0x58, 0xe8, 0x84, 0x21,
	0x7f, 0x49, 0x07, 0x1a, 0xb7, 0x1a, 0x38, 0x52, 0x7d, 0xf9, 0x31, 0x15, 0x82, 0x9c, 0x3b, 0x3c,
	0x47, 0xe2, 0x06, 0xa0, 0x83, 0x24, 0x8e, 0x69, 0x24, 0x5f, 0x08, 0x1a, 0x5b, 0x2f, 0xf0, 0xf7,
	0x60, 0x45, 0x91, 0xdd, 0xe8, 0x8c, 0x3b, 0xc7, 0x30, 0x2c, 0x7e, 0x3a, 0x24, 0x2c, 0xec, 0x0c,
	0x06, 0x31, 0x15, 0xc2, 0x7a, 0x96, 0xe3, 0xe1, 0x27, 0xb0, 0xa6, 0x8e, 0x89, 0x43, 0x1e, 0x5b,
	0x8f, 0x7f, 0x9a, 0xd0, 0xf8, 0x7a, 0xe6, 0xd8, 0x60, 0x92, 0x29, 0xb0, 0x01, 0xf9, 0xdf, 0x14,
	0xdc, 0x1d, 0x5c, 0xfc, 0x11, 0x20, 0x0d, 0x61, 0x15, 0xdb, 0xd0, 0xbd, 0x07, 0x95, 0x44, 0x71,
	0x9b, 0xa5, 0xcd, 0xb9, 0xed, 0xfa, 0xde, 0x9b, 0xbb, 0xb6, 0x4a, 0x76, 0xd3, 0x30, 0x98, 0xef,
	0xf8, 0x27, 0x70, 0xdf, 0x6a, 0xcb, 0x12, 0xa2, 0xbe, 0x17, 0x91, 0x4b, 0xe3, 0x69, 0x6d, 0x40,
	0x25, 0xe0, 0x21, 0x15, 0xcd, 0xf2, 0xe6, 0xdc, 0x76, 0x2d, 0x30, 0x04, 0xfe, 0x53, 0x09, 0xee,
	0x5b, 0x0f, 0xc6, 0x35, 0xde, 0xe1, 0x2d, 0x86, 0x45, 0x4b, 0x76, 0x06, 0x43, 0x16, 0x69, 0x77,
	0x97, 0x82, 0x1c, 0x0f, 0xed, 0x43, 0xd5, 0x1a, 0x21, 0x9a, 0x73, 0xda, 0xb9, 0x8d, 0xd4, 0xb9,
	0x89, 0x9e, 0x04, 0xa9, 0x3c, 0x16, 0x70, 0xef, 0x44, 0x89, 0x16, 0x0c, 0xdb, 0x00, 0xd0, 0x6c,
	0x03, 0x5a, 0x32, 0xf5, 0x99, 0x71, 0xd0, 0x87, 0x50, 0x33, 0x26, 0x30, 0xeb, 0xac, 0x8f, 0x39,
	0xd1, 0xd7, 0x20, 0x3b, 0x80, 0x7f, 0x5f, 0x52, 0x91, 0xa4, 0x67, 0x34, 0xa6, 0x51, 0x9f, 0x0a,
	0x55, 0xbb, 0x9f, 0xf1, 0x21, 0x7d, 0x11, 0x87, 0x36, 0x04, 0x8e, 0x54, 0x01, 0xed, 0x5d, 0xd0,
	0x34, 0xcd, 0x86, 0x40, 0x5b, 0xb0, 0xf4, 0x94, 0xf4, 0x2f, 0xcf, 0x63, 0x9e, 0x44, 0x03, 0x75,
	0x6a, 0x4e, 0x7f, 0xcd, 0x33, 0xd1, 0xfb, 0x50, 0x3b, 0x24, 0x57, 0x3c, 0x66, 0x92, 0x8a, 0xe6,
	0xbc, 0xb6, 0x71, 0x29, 0xb5, 0xf1, 0x98, 0x45, 0x97, 0x41, 0xf6, 0x1d, 0xff, 0xad, 0x04, 0x2b,
	0xd6, 0xee, 0x13, 0x2a, 0x25, 0x8b, 0xce, 0xc5, 0x0c, 0xd9, 0x39, 0x86, 0x07, 0xaa, 0x7a, 0x32,
	0x5f, 0x7a, 0x74, 0x38, 0x0a, 0x89, 0x34, 0xf6, 0xd6, 0xf7, 0x1a, 0x5e, 0x1e, 0x52, 0x77, 0x83,
	0x29, 0x67, 0x94, 0x5b, 0x07, 0x89, 0x90, 0x7c, 0xd8, 0xed, 0xf3, 0xc8, 0x73, 0x2b, 0xc7, 0x44,
	0x6f, 0x43, 0x45, 0x19, 0x3f, 0xc5, 0x25, 0xf3, 0x0d, 0xff, 0xab, 0x0c, 0x55, 0x57, 0xd7, 0xb3,
	0xf4, 0x35, 0xfa, 0x18, 0xea, 0x59, 0xbe, 0x84, 0x35, 0x7f, 0x3d, 0xd5, 0x3d, 0xa1, 0x46, 0x02,
	0xff, 0x00, 0x6a, 0x41, 0xf5, 0x30, 0x09, 0x43, 0x1d, 0x28, 0x63, 0x76, 0x4a, 0xa3, 0x75, 0xa8,
	0x1d, 0xb1, 0x2b, 0x1a, 0xe9, 0x8f, 0xf3, 0xfa, 0x63, 0xc6, 0x50, 0xa5, 0x76, 0x48, 0x86, 0x2c,
	0x34, 0x41, 0xae, 0xe8, 0xcf, 0x1e, 0x47, 0x9d, 0xee, 0x5c, 0x11, 0x49, 0x62, 0x15, 0x91, 0x37,
	0xcc, 0xe9, 0x94, 0xa1, 0x70, 0x3f, 0xe7, 0xa7, 0x3d, 0x26, 0x43, 0xda, 0x5c, 0x30, 0xb8, 0x8e,
	0x46, 0xef, 0xc2, 0xf2, 0x67, 0x44, 0x5c, 0xd0, 0xc1, 0x73, 0x22, 0xc4, 0x4b, 0x1e, 0x0f, 0x9a,
	0x55, 0x2d, 0x51, 0xe0, 0xa2, 0x8f, 0xcd, 0x55, 0xe8, 0xa5, 0xa8, 0x59, 0xbb, 0x25, 0x7d, 0x45,
	0x61, 0xfc, 0x1d, 0x68, 0x74, 0x46, 0xac, 0xc7, 0x2f, 0x69, 0x74, 0xcc, 0xcf, 0x59, 0xe4, 0xee,
	0x32, 0x55, 0xbc, 0x8a, 0x69, 0x03, 0x6e, 0x08, 0x7d, 0xbd, 0x84, 0x84, 0x45, 0x4a, 0x4b, 0x4e,
	0xbc, 0x65, 0x52, 0xe6, 0xd5, 0x5a, 0x4a, 0xab, 0x6f, 0xa9, 0x13, 0xa6, 0x15, 0x52, 0x1a, 0x9f,
	0xc1, 0x92, 0xd5, 0x93, 0x0d, 0x89, 0x93, 0xa4, 0xdf, 0x77, 0xa9, 0xae, 0x06, 0x8e, 0xcc, 0x2c,
	0x2a, 0x7b, 0x16, 0xa1, 0x77, 0x60, 0x5e, 0x01, 0xe9, 0xbc, 0x4d, 0xbc, 0x18, 0xf5, 0x67, 0xbc,
	0x0a, 0xcb, 0x5f, 0xd2, 0x58, 0xa5, 0xdb, 0xcd, 0x90, 0x36, 0xdc, 0xb3, 0x1c, 0x33, 0x46, 0x32,
	0x7c, 0xcb, 0x76, 0xed, 0x6c, 0x49, 0xbc, 0x0f, 0x0f, 0x0a, 0x4d, 0x36, 0xfb, 0xe0, 0x78, 0x5d,
	0x82, 0xe5, 0xce, 0x60, 0xe0, 0xcd, 0x30, 0x55, 0x1a, 0x8a, 0xd4, 0x85, 0x6c, 0x8f, 0x64, 0x8c,
	0xa2, 0xca, 0xf2, 0x78, 0xfb, 0x7e, 0x92, 0x2f, 0x7a, 0xe3, 0xff, 0x5d, 0xf7, 0x98, 0x7f, 0x04,
	0x3f, 0x82, 0x87, 0x9d, 0x2b, 0xc2, 0x42, 0x72, 0x1a, 0xd2, 0xc9, 0x9e, 0xe1, 0x00, 0x9a, 0xd3,
	0x44, 0xd0, 0xf7, 0xfd, 0x6b, 0xd4, 0xcc, 0xa5, 0x66, 0x11, 0x3e, 0xd5, 0xe7, 0x5d, 0xa0, 0xc7,
	0x30, 0xaf, 0xfa, 0x1c, 0xad, 0xc2, 0x5c, 0x76, 0x69, 0xaa, 0x9f, 0x08, 0xc1, 0xbc, 0xe7, 0xed,
	0xbc, 0xeb, 0xb0, 0x17, 0xdd, 0x2f, 0x19, 0x7d, 0xd9, 0xbb, 0x1e, 0xb9, 0xee, 0xf4, 0x38, 0xf8,
	0x09, 0xac, 0xd8, 0x79, 0xd0, 0x1d, 0xd0, 0x48, 0x32, 0x79, 0xad, 0x52, 0x68, 0xe1, 0x5d, 0x0a,
	0x2d, 0x39, 0x09, 0x00, 0xff, 0xa5, 0x0c, 0x0b, 0x56, 0x03, 0xda, 0x86, 0x72, 0xd7, 0x2c, 0x27,
	0xbe, 0x2f, 0x05, 0xfd, 0x41, 0xb9, 0x3b, 0x40, 0xdb, 0xb0, 0xd2, 0x49, 0x24, 0x1f, 0xea, 0x9d,
	0xab, 0xc7, 0x79, 0x68, 0xa6, 0x57, 0x2d, 0x28, 0xb2, 0x15, 0x66, 0x8f, 0x9c, 0x9b, 0x1b, 0xaf,
	0x16, 0xe8, 0xdf, 0xe8, 0x13, 0x80, 0x8e, 0x94, 0x31, 0x3b, 0x4d, 0xd4, 0xf5, 0x5e, 0xd1, 0xb1,
	0xdb, 0x2c, 0xe2, 0xed, 0x66, 0x22, 0x9f, 0x46, 0x32, 0xbe, 0x0e, 0xbc, 0x33, 0xe8, 0x43, 0xa8,
	0x1f, 0x13, 0x21, 0x5f, 0x8c, 0x06, 0x44, 0xd2, 0x81, 0xbe, 0x5a, 0xea, 0x7b, 0xad, 0x5d, 0xb3,
	0x12, 0xee, 0xba, 0x9d, 0x71, 0xb7, 0xe7, 0x76, 0xc6, 0xc0, 0x17, 0x6f, 0x7d, 0x04, 0x2b, 0x05,
	0xe5, 0x2a, 0x1b, 0x97, 0xd4, 0x05, 0x4c, 0xfd, 0x54, 0xfd, 0x76, 0x45, 0xc2, 0x24, 0x1d, 0x5f,
	0x9a, 0xd8, 0x2f, 0xff, 0xa0, 0x84, 0x7f, 0x05, 0x6f, 0xaa, 0x88, 0xf2, 0x88, 0x46, 0x59, 0xd4,
	0xf7, 0xd2, 0x30, 0xde, 0x19, 0xc0, 0x34, 0xde, 0x93, 0xf2, 0xf1, 0x0b, 0x53, 0x56, 0x5a, 0x39,
	0xda, 0xf1, 0x12, 0xd2, 0xca, 0x15, 0x57, 0x0e, 0x5c, 0xa7, 0x64, 0x13, 0xea, 0xcf, 0xa8, 0xe8,
	0xc7, 0x6c, 0xa4, 0x82, 0xef, 0x5a, 0xc6, 0x63, 0xe1, 0x21, 0x2c, 0x1c, 0x52, 0x22, 0x93, 0x98,
	0xa2, 0xe5, 0x54, 0xf1, 0xa2, 0x3e, 0x3c, 0xa9, 0xf4, 0x6c, 0x0f, 0x5a, 0x24, 0x5d, 0x7b, 0x8b,
	0x81, 0xcf, 0x52, 0x3d, 0x9c, 0xfa, 0xe6, 0x86, 0x43, 0xca, 0xc0, 0xff, 0x2e, 0x43, 0xb5, 0x47,
	0x85, 0xec, 0x13, 0x31, 0x1b, 0xe0, 0x16, 0x2c, 0x65, 0xd5, 0xf3, 0x23, 0x7a, 0xed, 0x66, 0x68,
	0x8e, 0xa9, 0x26, 0x43, 0xbe, 0xc6, 0x2c, 0x72, 0x81, 0x5b, 0x34, 0xbf, 0x32, 0x6e, 0x7e, 0x13,
	0x16, 0x9e, 0xd1, 0x90, 0xba, 0x02, 0xaa, 0x06, 0x8e, 0x44, 0x3b, 0xb0, 0xda, 0x1d, 0x8e, 0x78,
	0x2c, 0x49, 0xd4, 0xa7, 0x01, 0x51, 0x3d, 0xac, 0x27, 0x54, 0x25, 0x18, 0xe3, 0x2b, 0xab, 0xbb,
	0x11, 0xe9, 0x4b, 0x76, 0x45, 0xbf, 0xe0, 0xaa, 0x9e, 0xab, 0xba, 0xd2, 0xf3, 0xcc, 0x7c, 0xa8,
	0x6a, 0x85, 0x50, 0xa9, 0x76, 0x3a, 0x91, 0xe4, 0x94, 0x85, 0x2a, 0x99, 0x06, 0x0e, 0x34, 0x5c,
	0x91, 0xad, 0xaa, 0xf2, 0x44, 0xd2, 0x91, 0x68, 0xd6, 0xcd, 0x96, 0xaa, 0x89, 0xb4, 0xc9, 0x16,
	0xb3, 0x26, 0xc3, 0x6d, 0xa8, 0xa9, 0xe8, 0x8f, 0x42, 0x12, 0x89, 0x59, 0xc2, 0x8f, 0x5f, 0xdb,
	0x7c, 0xc5, 0xc9, 0x6c, 0x07, 0xf2, 0x3e, 0xcd, 0x15, 0x7d, 0x6a, 0x40, 0xe5, 0x69, 0xc2, 0x42,
	0x57, 0x18, 0x86, 0x40, 0xfb, 0x00, 0x41, 0x12, 0x9d, 0x48, 0x12, 0xab, 0xb0, 0x57, 0xee, 0xec,
	0x5b, 0x4f, 0x5a, 0x35, 0x7d, 0x90, 0x44, 0x87, 0x2c, 0x62, 0x6a, 0x05, 0x98, 0xa5, 0xe9, 0x3d,
	0x71, 0x13, 0x39, 0xb5, 0xde, 0x99, 0x55, 0xc3, 0x10, 0xea, 0x7e, 0x75, 0x51, 0xea, 0xba, 0x1d,
	0xc3, 0xe3, 0xec, 0xfd, 0xa7, 0x0c, 0xf3, 0xea, 0x2d, 0x87, 0xfe, 0x58, 0x82, 0x45, 0xff, 0x59,
	0x87, 0xb2, 0x05, 0x6b, 0xc2, 0x43, 0xb3, 0xf5, 0xed, 0x29, 0x5f, 0xcd, 0x98, 0xc5, 0x47, 0xdf,
	0xfc, 0xfd, 0x9f, 0x7f, 0x28, 0x77, 0xd0, 0x13, 0xf3, 0x7c, 0x4d, 0xe4, 0x45, 0x9b, 0x79, 0x72,
	0xed, 0x57, 0xde, 0xa8, 0xbb, 0x69, 0xbf, 0xf2, 0xde, 0x29, 0x8a, 0x4a, 0x87, 0xd8, 0x0d, 0x12,
	0xb0, 0xac, 0x17, 0x88, 0x9f, 0x31, 0x79, 0x61, 0x36, 0x82, 0x0c, 0x79, 0xd2, 0x62, 0xd3, 0x7a,
	0x90, 0xed, 0x9c, 0xfe, 0xe2, 0x81, 0x77, 0xb4, 0x45, 0x5b, 0x08, 0x67, 0x16, 0x85, 0x4a, 0xe0,
	0xf1, 0x4b, 0x26, 0x2f, 0x1e, 0x4b, 0xa5, 0xa7, 0xfd, 0x4a, 0xab, 0xbb, 0x41, 0x5f, 0x41, 0x23,
	0x05, 0x3d, 0x88, 0xa9, 0xbe, 0x85, 0x48, 0x28, 0x90, 0xf7, 0x74, 0x99, 0xb4, 0x25, 0x4d, 0xc5,
	0x6e, 0x69, 0xec, 0x06, 0x5e, 0x29, 0x60, 0xef, 0x97, 0x76, 0xf6, 0xfe, 0x5a, 0x81, 0x8a, 0x7e,
	0x11, 0xa2, 0xdf, 0x00, 0x3a, 0xa2, 0xd2, 0x7b, 0x0e, 0xeb, 0x05, 0x79, 0x2d, 0xbb, 0x16, 0xc7,
	0x1e, 0xca, 0xad, 0xf1, 0x7d, 0xc8, 0x61, 0x21, 0xa4, 0xb1, 0xf4, 0xab, 0xb1, 0xdd, 0x37, 0x27,
	0xd1, 0x29, 0xd4, 0x8f, 0x68, 0xa6, 0xba, 0x39, 0xbe, 0x4d, 0x4d, 0xd7, 0xfb, 0xae, 0xd6, 0xbb,
	0x89, 0x36, 0x3c, 0xbd, 0x2c, 0x3a, 0xe3, 0xed, 0x57, 0xfe, 0xae, 0x7e, 0x83, 0x7e, 0x57, 0xd2,
	0x6e, 0x14, 0x1e, 0xe2, 0x68, 0x2b, 0xa7, 0x71, 0xca, 0x13, 0xbd, 0xb5, 0x96, 0x97, 0xca, 0x3d,
	0x92, 0xf1, 0xfb, 0xda, 0x82, 0x77, 0xd0, 0xdb, 0x9e, 0x05, 0xa7, 0xd7, 0x8f, 0xfb, 0x46, 0x4f,
	0xbe, 0xa4, 0xd0, 0xeb, 0xbc, 0x19, 0x6e, 0x22, 0x8d, 0x9b, 0x31, 0xe1, 0xa1, 0x7f, 0xbb, 0x19,
	0x3f, 0xd4, 0x66, 0x7c, 0x80, 0xbe, 0x9b, 0x37, 0x63, 0x64, 0xf4, 0xdc, 0x56, 0xd9, 0xe8, 0xe7,
	0x00, 0x66, 0x44, 0x2b, 0xb5, 0x68, 0x3c, 0xc8, 0x93, 0xe2, 0xbe, 0xa5, 0xe1, 0x36, 0x5a, 0x6f,
	0x79, 0x70, 0xf9, 0x90, 0xef, 0x97, 0x76, 0x50, 0x04, 0xab, 0x76, 0xff, 0xec, 0x71, 0x17, 0xf2,
	0x6f, 0x65, 0x8d, 0x92, 0x5b, 0x4d, 0x27, 0xa1, 0xec, 0x6a, 0x94, 0x6d, 0x3c, 0x4b, 0x6c, 0x55,
	0xd5, 0xfe, 0x63, 0x2e, 0x5d, 0xc2, 0x50, 0x62, 0xea, 0xb6, 0xb0, 0x3e, 0x3e, 0x9c, 0xba, 0x2b,
	0x5a, 0x2b, 0xa6, 0x2e, 0x93, 0xce, 0x65, 0xb4, 0xae, 0x8d, 0xe9, 0xbb, 0xcd, 0xb2, 0x90, 0xe1,
	0x6f, 0x4a, 0xb0, 0x76, 0x44, 0xe5, 0xd4, 0xfd, 0x75, 0x3b, 0x73, 0xff, 0xf6, 0x2d, 0xb8, 0xf5,
	0xe8, 0x4e, 0x49, 0xfc, 0x40, 0x9b, 0xb4, 0x8a, 0x96, 0xf3, 0x26, 0x21, 0x09, 0xf7, 0x4d, 0x46,
	0x8b, 0xe8, 0x53, 0xbd, 0xbb, 0xc5, 0xef, 0xf7, 0x34, 0xc8, 0xa3, 0xd6, 0xad, 0x7e, 0xab, 0x6c,
	0x9f, 0xc1, 0xfd, 0x83, 0x98, 0xfe, 0x9f, 0x50, 0xdf, 0xd2, 0xa8, 0xf7, 0x70, 0xc1, 0x35, 0x95,
	0xe5, 0x8b, 0xf4, 0xb1, 0x84, 0x7e, 0x0d, 0xcb, 0x47, 0x54, 0xaa, 0x67, 0xb3, 0xe3, 0x64, 0xe5,
	0x95, 0x7f, 0x79, 0xb5, 0xd6, 0x8b, 0x1f, 0xfc, 0x07, 0x18, 0x6e, 0x68, 0xb8, 0x65, 0xb4, 0xa8,
	0xe1, 0xae, 0x8c, 0xc4, 0xd3, 0x67, 0xb0, 0xd6, 0xe7, 0xc3, 0xf4, 0x60, 0x3f, 0x64, 0x34, 0x92,
	0xe9, 0xc8, 0xfb, 0xa5, 0xfb, 0xd7, 0xf4, 0xcf, 0xe5, 0xdb, 0xc4, 0x4e, 0xdf, 0xd0, 0xbf, 0x3e,
	0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x0c, 0x99, 0xa3, 0x72, 0x15, 0x00, 0x00,
}
