/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    const ApiClient = require('../ApiClient'),
     SlickqaVersionInfoResponse = require('../model/SlickqaVersionInfoResponse');

  /**
   * Version service.
   * @module api/VersionApi
   * @version 0.1.0
   */

  /**
   * Constructs a new VersionApi. 
   * @alias module:api/VersionApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getFullVersion operation.
     * @callback module:api/VersionApi~getFullVersionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SlickqaVersionInfoResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/VersionApi~getFullVersionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SlickqaVersionInfoResponse}
     */
    this.getFullVersion = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SlickqaVersionInfoResponse;

      return this.apiClient.callApi(
        '/api/version', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  module.exports = exports;
