/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require('./ApiClient'),
 SlickqaCompanyPermissionInfo = require('./model/SlickqaCompanyPermissionInfo'),
 SlickqaIsAuthorizedResponse = require('./model/SlickqaIsAuthorizedResponse'),
 SlickqaLoginResponse = require('./model/SlickqaLoginResponse'),
 SlickqaProjectPermissionInfo = require('./model/SlickqaProjectPermissionInfo'),
 SlickqaSlickPermissionInfo = require('./model/SlickqaSlickPermissionInfo'),
 SlickqaUserInfo = require('./model/SlickqaUserInfo'),
 SlickqaUsersQueryResponse = require('./model/SlickqaUsersQueryResponse'), AuthApi = require('./api/AuthApi'), UsersApi = require('./api/UsersApi')


  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var SlickClient = require('index'); // See note below*.
   * var xxxSvc = new SlickClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new SlickClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new SlickClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new SlickClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The SlickqaCompanyPermissionInfo model constructor.
     * @property {module:model/SlickqaCompanyPermissionInfo}
     */
    SlickqaCompanyPermissionInfo: SlickqaCompanyPermissionInfo,
    /**
     * The SlickqaIsAuthorizedResponse model constructor.
     * @property {module:model/SlickqaIsAuthorizedResponse}
     */
    SlickqaIsAuthorizedResponse: SlickqaIsAuthorizedResponse,
    /**
     * The SlickqaLoginResponse model constructor.
     * @property {module:model/SlickqaLoginResponse}
     */
    SlickqaLoginResponse: SlickqaLoginResponse,
    /**
     * The SlickqaProjectPermissionInfo model constructor.
     * @property {module:model/SlickqaProjectPermissionInfo}
     */
    SlickqaProjectPermissionInfo: SlickqaProjectPermissionInfo,
    /**
     * The SlickqaSlickPermissionInfo model constructor.
     * @property {module:model/SlickqaSlickPermissionInfo}
     */
    SlickqaSlickPermissionInfo: SlickqaSlickPermissionInfo,
    /**
     * The SlickqaUserInfo model constructor.
     * @property {module:model/SlickqaUserInfo}
     */
    SlickqaUserInfo: SlickqaUserInfo,
    /**
     * The SlickqaUsersQueryResponse model constructor.
     * @property {module:model/SlickqaUsersQueryResponse}
     */
    SlickqaUsersQueryResponse: SlickqaUsersQueryResponse,
    /**
     * The AuthApi service constructor.
     * @property {module:api/AuthApi}
     */
    AuthApi: AuthApi,
    /**
     * The UsersApi service constructor.
     * @property {module:api/UsersApi}
     */
    UsersApi: UsersApi
  };

module.exports = exports;
