/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    , SlickqaLink = require('./SlickqaLink'), SlickqaPreferences = require('./SlickqaPreferences')





  /**
   * The SlickqaCompanySettings model module.
   * @module model/SlickqaCompanySettings
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SlickqaCompanySettings</code>.
   * @alias module:model/SlickqaCompanySettings
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>SlickqaCompanySettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SlickqaCompanySettings} obj Optional instance to populate.
   * @return {module:model/SlickqaCompanySettings} The populated <code>SlickqaCompanySettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('CompanyName')) {
        obj['CompanyName'] = ApiClient.convertToType(data['CompanyName'], 'String');
      }
      if (data.hasOwnProperty('UserPreferenceTemplate')) {
        obj['UserPreferenceTemplate'] = SlickqaPreferences.constructFromObject(data['UserPreferenceTemplate']);
      }
      if (data.hasOwnProperty('CustomIconUrl')) {
        obj['CustomIconUrl'] = ApiClient.convertToType(data['CustomIconUrl'], 'String');
      }
      if (data.hasOwnProperty('Links')) {
        obj['Links'] = ApiClient.convertToType(data['Links'], [SlickqaLink]);
      }
    }
    return obj;
  }

  /**
   * @member {String} CompanyName
   */
  exports.prototype['CompanyName'] = undefined;
  /**
   * @member {module:model/SlickqaPreferences} UserPreferenceTemplate
   */
  exports.prototype['UserPreferenceTemplate'] = undefined;
  /**
   * @member {String} CustomIconUrl
   */
  exports.prototype['CustomIconUrl'] = undefined;
  /**
   * @member {Array.<module:model/SlickqaLink>} Links
   */
  exports.prototype['Links'] = undefined;



  module.exports = exports;



