/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    





  /**
   * The SlickqaProjectPermissionInfo model module.
   * @module model/SlickqaProjectPermissionInfo
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SlickqaProjectPermissionInfo</code>.
   * @alias module:model/SlickqaProjectPermissionInfo
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SlickqaProjectPermissionInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SlickqaProjectPermissionInfo} obj Optional instance to populate.
   * @return {module:model/SlickqaProjectPermissionInfo} The populated <code>SlickqaProjectPermissionInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ProjectName')) {
        obj['ProjectName'] = ApiClient.convertToType(data['ProjectName'], 'String');
      }
      if (data.hasOwnProperty('Roles')) {
        obj['Roles'] = ApiClient.convertToType(data['Roles'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} ProjectName
   */
  exports.prototype['ProjectName'] = undefined;
  /**
   * @member {Array.<String>} Roles
   */
  exports.prototype['Roles'] = undefined;



  module.exports = exports;



