/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    





  /**
   * The SlickqaLink model module.
   * @module model/SlickqaLink
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SlickqaLink</code>.
   * @alias module:model/SlickqaLink
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>SlickqaLink</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SlickqaLink} obj Optional instance to populate.
   * @return {module:model/SlickqaLink} The populated <code>SlickqaLink</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Url')) {
        obj['Url'] = ApiClient.convertToType(data['Url'], 'String');
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('UIViewType')) {
        obj['UIViewType'] = ApiClient.convertToType(data['UIViewType'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} Url
   */
  exports.prototype['Url'] = undefined;
  /**
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * @member {String} UIViewType
   */
  exports.prototype['UIViewType'] = undefined;



  module.exports = exports;



