/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    , SlickqaPreferences = require('./SlickqaPreferences'), SlickqaSlickPermissionInfo = require('./SlickqaSlickPermissionInfo')





  /**
   * The SlickqaUserInfo model module.
   * @module model/SlickqaUserInfo
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SlickqaUserInfo</code>.
   * @alias module:model/SlickqaUserInfo
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>SlickqaUserInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SlickqaUserInfo} obj Optional instance to populate.
   * @return {module:model/SlickqaUserInfo} The populated <code>SlickqaUserInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('EmailAddress')) {
        obj['EmailAddress'] = ApiClient.convertToType(data['EmailAddress'], 'String');
      }
      if (data.hasOwnProperty('Permissions')) {
        obj['Permissions'] = SlickqaSlickPermissionInfo.constructFromObject(data['Permissions']);
      }
      if (data.hasOwnProperty('FullName')) {
        obj['FullName'] = ApiClient.convertToType(data['FullName'], 'String');
      }
      if (data.hasOwnProperty('GivenName')) {
        obj['GivenName'] = ApiClient.convertToType(data['GivenName'], 'String');
      }
      if (data.hasOwnProperty('FamilyName')) {
        obj['FamilyName'] = ApiClient.convertToType(data['FamilyName'], 'String');
      }
      if (data.hasOwnProperty('AvatarUrl')) {
        obj['AvatarUrl'] = ApiClient.convertToType(data['AvatarUrl'], 'String');
      }
      if (data.hasOwnProperty('JobTitle')) {
        obj['JobTitle'] = ApiClient.convertToType(data['JobTitle'], 'String');
      }
      if (data.hasOwnProperty('HashedPassword')) {
        obj['HashedPassword'] = ApiClient.convertToType(data['HashedPassword'], 'String');
      }
      if (data.hasOwnProperty('UserPreferences')) {
        obj['UserPreferences'] = SlickqaPreferences.constructFromObject(data['UserPreferences']);
      }
    }
    return obj;
  }

  /**
   * @member {String} EmailAddress
   */
  exports.prototype['EmailAddress'] = undefined;
  /**
   * @member {module:model/SlickqaSlickPermissionInfo} Permissions
   */
  exports.prototype['Permissions'] = undefined;
  /**
   * @member {String} FullName
   */
  exports.prototype['FullName'] = undefined;
  /**
   * @member {String} GivenName
   */
  exports.prototype['GivenName'] = undefined;
  /**
   * @member {String} FamilyName
   */
  exports.prototype['FamilyName'] = undefined;
  /**
   * @member {String} AvatarUrl
   */
  exports.prototype['AvatarUrl'] = undefined;
  /**
   * @member {String} JobTitle
   */
  exports.prototype['JobTitle'] = undefined;
  /**
   * @member {String} HashedPassword
   */
  exports.prototype['HashedPassword'] = undefined;
  /**
   * @member {module:model/SlickqaPreferences} UserPreferences
   */
  exports.prototype['UserPreferences'] = undefined;



  module.exports = exports;



