/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    





  /**
   * The SlickqaIsAuthorizedResponse model module.
   * @module model/SlickqaIsAuthorizedResponse
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SlickqaIsAuthorizedResponse</code>.
   * @alias module:model/SlickqaIsAuthorizedResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SlickqaIsAuthorizedResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SlickqaIsAuthorizedResponse} obj Optional instance to populate.
   * @return {module:model/SlickqaIsAuthorizedResponse} The populated <code>SlickqaIsAuthorizedResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Allowed')) {
        obj['Allowed'] = ApiClient.convertToType(data['Allowed'], 'Boolean');
      }
      if (data.hasOwnProperty('Message')) {
        obj['Message'] = ApiClient.convertToType(data['Message'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} Allowed
   */
  exports.prototype['Allowed'] = undefined;
  /**
   * @member {String} Message
   */
  exports.prototype['Message'] = undefined;



  module.exports = exports;



