/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    , SlickqaUserInfo = require('./SlickqaUserInfo')





  /**
   * The SlickqaUsersQueryResponse model module.
   * @module model/SlickqaUsersQueryResponse
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SlickqaUsersQueryResponse</code>.
   * @alias module:model/SlickqaUsersQueryResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>SlickqaUsersQueryResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SlickqaUsersQueryResponse} obj Optional instance to populate.
   * @return {module:model/SlickqaUsersQueryResponse} The populated <code>SlickqaUsersQueryResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('users')) {
        obj['users'] = ApiClient.convertToType(data['users'], [SlickqaUserInfo]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/SlickqaUserInfo>} users
   */
  exports.prototype['users'] = undefined;



  module.exports = exports;



