/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    





  /**
   * The SlickqaPreferences model module.
   * @module model/SlickqaPreferences
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SlickqaPreferences</code>.
   * @alias module:model/SlickqaPreferences
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>SlickqaPreferences</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SlickqaPreferences} obj Optional instance to populate.
   * @return {module:model/SlickqaPreferences} The populated <code>SlickqaPreferences</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('HomeUrl')) {
        obj['HomeUrl'] = ApiClient.convertToType(data['HomeUrl'], 'String');
      }
      if (data.hasOwnProperty('Theme')) {
        obj['Theme'] = ApiClient.convertToType(data['Theme'], 'String');
      }
      if (data.hasOwnProperty('BackgroundUrl')) {
        obj['BackgroundUrl'] = ApiClient.convertToType(data['BackgroundUrl'], 'String');
      }
      if (data.hasOwnProperty('Favorites')) {
        obj['Favorites'] = ApiClient.convertToType(data['Favorites'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} HomeUrl
   */
  exports.prototype['HomeUrl'] = undefined;
  /**
   * @member {String} Theme
   */
  exports.prototype['Theme'] = undefined;
  /**
   * @member {String} BackgroundUrl
   */
  exports.prototype['BackgroundUrl'] = undefined;
  /**
   * @member {Array.<String>} Favorites
   */
  exports.prototype['Favorites'] = undefined;



  module.exports = exports;



