/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    , SlickqaProjectPermissionInfo = require('./SlickqaProjectPermissionInfo')





  /**
   * The SlickqaCompanyPermissionInfo model module.
   * @module model/SlickqaCompanyPermissionInfo
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SlickqaCompanyPermissionInfo</code>.
   * @alias module:model/SlickqaCompanyPermissionInfo
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>SlickqaCompanyPermissionInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SlickqaCompanyPermissionInfo} obj Optional instance to populate.
   * @return {module:model/SlickqaCompanyPermissionInfo} The populated <code>SlickqaCompanyPermissionInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('CompanyName')) {
        obj['CompanyName'] = ApiClient.convertToType(data['CompanyName'], 'String');
      }
      if (data.hasOwnProperty('CompanyAdmin')) {
        obj['CompanyAdmin'] = ApiClient.convertToType(data['CompanyAdmin'], 'Number');
      }
      if (data.hasOwnProperty('Projects')) {
        obj['Projects'] = ApiClient.convertToType(data['Projects'], [SlickqaProjectPermissionInfo]);
      }
    }
    return obj;
  }

  /**
   * @member {String} CompanyName
   */
  exports.prototype['CompanyName'] = undefined;
  /**
   * @member {Number} CompanyAdmin
   */
  exports.prototype['CompanyAdmin'] = undefined;
  /**
   * @member {Array.<module:model/SlickqaProjectPermissionInfo>} Projects
   */
  exports.prototype['Projects'] = undefined;



  module.exports = exports;



