/**
 * slick.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    , SlickqaCompanyPermissionInfo = require('./SlickqaCompanyPermissionInfo')





  /**
   * The SlickqaAddUserRequest model module.
   * @module model/SlickqaAddUserRequest
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SlickqaAddUserRequest</code>.
   * @alias module:model/SlickqaAddUserRequest
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>SlickqaAddUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SlickqaAddUserRequest} obj Optional instance to populate.
   * @return {module:model/SlickqaAddUserRequest} The populated <code>SlickqaAddUserRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('UserEmail')) {
        obj['UserEmail'] = ApiClient.convertToType(data['UserEmail'], 'String');
      }
      if (data.hasOwnProperty('CompanyName')) {
        obj['CompanyName'] = ApiClient.convertToType(data['CompanyName'], 'String');
      }
      if (data.hasOwnProperty('Permissions')) {
        obj['Permissions'] = SlickqaCompanyPermissionInfo.constructFromObject(data['Permissions']);
      }
    }
    return obj;
  }

  /**
   * @member {String} UserEmail
   */
  exports.prototype['UserEmail'] = undefined;
  /**
   * @member {String} CompanyName
   */
  exports.prototype['CompanyName'] = undefined;
  /**
   * @member {module:model/SlickqaCompanyPermissionInfo} Permissions
   */
  exports.prototype['Permissions'] = undefined;



  module.exports = exports;



